### ISSUE TITLE
Stuck somewhere/somehow during installation .chondro.wl not found

### ISSUE THREAD

**Issue by bryanhanson** [cbeleites/hyperSpec#111]
I'm on the latest master branch.  If I do `make bootstrap` everything seems to proceed just fine until we get around to roxygenizing, when I see (this is the last part of the output):

> * DONE (baseline)
> 
> The downloaded source packages are in
> 	'/private/var/folders/f4/5smpz_448xj3_l0059_zm20h0000gn/T/RtmpjY2ZY0/downloaded_packages'
> update DESCRIPTION
> Roxygenize
> Updating hyperSpec documentation
> Loading hyperSpec
> Loading required package: lattice
> Loading required package: grid
> Loading required package: ggplot2
> Loading required package: xml2
> Creating a generic function for 'apply' from package 'base' in package 'hyperSpec'
> Creating a generic function for 'cov' from package 'stats' in package 'hyperSpec'
> Creating a generic function for 'ncol' from package 'base' in package 'hyperSpec'
> Creating a generic function for 'nrow' from package 'base' in package 'hyperSpec'
> Creating a generic function for 'rownames' from package 'base' in package 'hyperSpec'
> Creating a generic function for 'rownames<-' from package 'base' in package 'hyperSpec'
> Creating a generic function for 'colnames' from package 'base' in package 'hyperSpec'
> Creating a generic function for 'colnames<-' from package 'base' in package 'hyperSpec'
> Creating a generic function for 'sample' from package 'base' in package 'hyperSpec'
> Creating a generic function for 'sweep' from package 'base' in package 'hyperSpec'
> Package hyperSpec, version 0.99-20200319
> 
> To get started, try
>    vignette ("hyperspec")
>    package?hyperSpec 
>    vignette (package = "hyperSpec")
> 
> If you use this package please cite it appropriately.
>    citation("hyperSpec")
> will give you the correct reference.
> 
> The project homepage is http://hyperspec.r-forge.r-project.org
> 
> 
> Error in .local(.Object, ...) : object '.chondro.wl' not found
> Calls: document ... .make.chondro -> new -> initialize -> initialize -> .local
> Execution halted
> make: *** [roxygenize] Error 1

Looking at `chondro.R` I see mention of the missing object, as well as others.  A little grepping suggests these objects are not in my local repo nor the remote repo. 

I'm a wee bit confused, are we completely missing a piece of code or data?

**Comment by ximeg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue with build system (Sysdata.RDA)](https://trello.com/c/w88MSAfD/38-issue-with-build-system-sysdatarda)

**Comment by cbeleites** [comment]
likely the same as #104

**Comment by eoduniyi** [comment]
Yeah, I'm having this issue too

**Comment by cbeleites** [comment]
This should be fixed in bugfix/104-make-trouble.

Left to do: check that all Dependencies and Suggestions are installed during `make bootstrap`
