### ISSUE TITLE
Contributor's guide for hyperSpec

### ISSUE THREAD

**Issue by ximeg** [cbeleites/hyperSpec#112]
### Why contributor's guide is a good idea?
How to contribute to the project? What git branches to use? How the code review is conducted? These are stumbling blocks for many developers.

Therefore it is paramount to have an established set of simple and logical, but strict rules that everybody has to follow. Their violation often leads to unpleasant surprises, misunderstanding, and can result in an unexpected urgent work for some of the team members to bring the project back on track. And this can be very bad.

This is why a we need a contributor's guide in a written form.

### How to make one?

There is an article on GitHub that outlines the recommended approach - [Setting guidelines for repository contributors](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors)

### What questions should be addressed?

* Rules of git use in the project - nobody commits directly to master, instead we work with branches according to the [git flow model](https://nvie.com/posts/a-successful-git-branching-model/).
* Core review - pull requests are subjects to review via pull requests
* Traceability - issues are opened for the community to discuss the work to be done before it is done. These issues are linked to the feature or bugfix branches and pull requests.
* Licensing - contributors understand that their work forever becomes the part of the hyperSpec project and is going to be licensed under free open source license

**Comment by ximeg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make a draft of the contributor's guide](https://trello.com/c/J0qI21oT/29-make-a-draft-of-the-contributors-guide)

**Comment by ximeg** [comment]
I like this idea of including emoji into the commit messages that I discovered in the [Atom's guidelines](https://github.com/atom/atom/blob/master/CONTRIBUTING.md). GitHub renders them as pictures.

> * Consider starting the commit message with an applicable emoji:
    * :art: `:art:` when improving the format/structure of the code
    * :racehorse: `:racehorse:` when improving performance
    * :non-potable_water: `:non-potable_water:` when plugging memory leaks
    * :memo: `:memo:` when writing docs
    * :penguin: `:penguin:` when fixing something on Linux
    * :apple: `:apple:` when fixing something on macOS
    * :checkered_flag: `:checkered_flag:` when fixing something on Windows
    * :bug: `:bug:` when fixing a bug
    * :fire: `:fire:` when removing code or files
    * :green_heart: `:green_heart:` when fixing the CI build
    * :white_check_mark: `:white_check_mark:` when adding tests
    * :lock: `:lock:` when dealing with security
    * :arrow_up: `:arrow_up:` when upgrading dependencies
    * :arrow_down: `:arrow_down:` when downgrading dependencies
    * :shirt: `:shirt:` when removing linter warnings

### Do we want to use this practice in our project?

**Comment by cbeleites** [comment]
I'd prefer to use a more directly descriptive "tag" verb. Either something like  
`bugfix: ...` or `fix issue #... : <explanation`, `refactor ...`. 
Possibly also because I do a good part of my git work in the shell.

**Comment by bryanhanson** [comment]
I’m OK with any useful scheme, but like Claudia I do all my git work in the shell so shorter is better.

**Comment by bryanhanson** [comment]
We have a solid CONTRIBUTING.md so can we close this issue?  Obviously we can make changes in the future but the basic principles seem to be established.

**Comment by ximeg** [comment]
Yes, I agree, it's done and may need only small polishing in the future!
