### ISSUE TITLE
Update hyperChemoBridge

### ISSUE THREAD

**Issue by bryanhanson** [cbeleites/hyperSpec#115]
Update this helper package near the end of GSOC.

**Comment by bryanhanson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update hyperChemoBridge near end of GSOC](https://trello.com/c/v1MPD8Nl/47-update-hyperchemobridge-near-end-of-gsoc)

**Comment by cbeleites** [comment]
I'm closing this here since I created an issue for this over at https://github.com/Chathurga/HyperChemoBridge/issues/1
