### ISSUE TITLE
fileio.Rnw chunk readcollapse has an error

### ISSUE THREAD

**Issue by bryanhanson** [cbeleites/hyperSpec#119]
As I'm pushing deeper into getting the `Makefile` to behave, when I run `make bootstrap` (after a local fix to the `-daytime` issue, part of #104 and #111), I see the following error which arises when one does `spc <- lapply (files, read.spc)` (either via the `Makefile` or manually, step by step) in the `readcollapse` chunk of `fileio.Rnw`:

```
spc <- lapply (files, read.spc)
Error in length(pos) == 1 && pos[[1]] == -1 : 
  'length(x) = 52 > 1' in coercion to 'logical(1)'
```

**Comment by cbeleites** [comment]
*readcollapse* is the first chunk that uses a file stored with `git lfs`. 

- is `git lfs` installed and initialized?
- in case `git lfs` was not available locally when you cloned the **hyperSpec** repo, you'll need to `git lfs pull` to retrieve the files stored under `git lfs`.
- in case `git lfs` is working properly and you do have the spectra files (and not only the pointer files), can you post a `traceback()`, please?

**Comment by bryanhanson** [comment]
We did some troubleshooting tonight so @cbeleites  has some more info when she comes on.

I deleted my `hyperSpec` repo and did the following:

```
Research/R_Pkgs> git clone https://github.com/cbeleites/hyperSpec
Research/R_Pkgs> cd hyperSpec
R_Pkgs/hyperSpec(master)> git checkout develop
R_Pkgs/hyperSpec(develop)> git lfs pull                                                                  
R_Pkgs/hyperSpec(develop)> make bootstrap
```

and then I get the same error as originally reported:
```
-n checking required & suggested packages ... 
OK
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C hyperSpec/data
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../../Vignettes/fileio 
cp -av ../vignettes.defs vignettes.defs
../vignettes.defs -> vignettes.defs
R CMD Sweave fileio.Rnw --pdf --compact="both" 

>>>  Loading Bryan's .Rprofile

Loading required package: lattice
Loading required package: grid
Loading required package: ggplot2
Loading required package: xml2
Package hyperSpec, version 0.99-20200213.1

To get started, try
   vignette ("hyperspec")
   package?hyperSpec 
   vignette (package = "hyperSpec")

If you use this package please cite it appropriately.
   citation("hyperSpec")
will give you the correct reference.

The project homepage is http://hyperspec.r-forge.r-project.org



Error:  chunk 10 (label = readcollapse) 
Error in length(pos) == 1 && pos[[1]] == -1 : 
  'length(x) = 52 > 1' in coercion to 'logical(1)'
Execution halted
make[2]: *** [fileio.pdf] Error 1
make[1]: *** [../../Vignettes/fileio/barbiturates.rda] Error 2
make: *** [pkg-data] Error 2
```

**Comment by eoduniyi** [comment]
Echoing what @bryanhanson posted:
<img width="1437" alt="Screen Shot 2020-05-13 at 7 13 40 PM" src="https://user-images.githubusercontent.com/31193655/81883924-1e884b80-955c-11ea-9d2c-cbb4dc5cae62.png">

**Comment by GegznaV** [comment]
@cbeleites, @bryanhanson Is this issue still relevant? Could it be closed?

**Comment by bryanhanson** [comment]
I think we can close -- I don't use or attempt to use `make` anymore.
