### ISSUE TITLE
Changes in `apply` signature

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#126]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_hyperSpec.html>.

The problems in r-devel are from

  * apply() gains a simplify argument to possibly disable simplifying
    results.

To fix the code, it may be simplest to conditionalize your setMethod()
calls according to whether apply() has a simplify argument or not.  I
would perhaps do something like
```r
  my_apply_method <- .....

  if("simplify" %in% names(formals(base::apply))) 
     setMethod("apply", signature(.......),
               function(X, MARGIN, FUN, ..., simplify = TRUE)
                    my_apply_method(X, MARGIN, FUN, ...))
  else
     setMethod("apply", signature(.......),
               function(X, MARGIN, FUN, ...)
                    my_apply_method(X, MARGIN, FUN, ...))
```
or appropriate variants thereof.

Codoc mismatches in Rd files are a nuisance: in principle you could also
conditionalize your Rd code along the above lines via \Sexpr{}, but in
cases where these methods do not add new arguments, you could simply
comment out the \usage entries.

Please correct before 2020-05-29 to safely retain your package on CRAN.

Best,
-k

**Comment by eoduniyi** [comment]
I can successfully make, build, and check/test hyperSpec on R 4.1, so going to close this now...
