### ISSUE TITLE
Should we add a NEWS.md file?

### ISSUE THREAD

**Issue by bryanhanson** [cbeleites/hyperSpec#127]
A nice feature for users is some kind of news or changelog file. `hyperSpec` does not currently have one.  Shall we add one?  If so, we should also add reminders to `CONTRIBUTING.md` to add significant changes to `NEWS.md`.  I'm glad to set it up if this proposal is approved. Simple enough it's probably not even worthy of a branch.

**Comment by bryanhanson** [comment]
I should add that `NEWS.md` should start at the end of summer "big release".

**Comment by cbeleites** [comment]
I think it should already include the big changes of the summer...

**Comment by bryanhanson** [comment]
I started a branch for this, now we need to remember to add to `NEWS.md`.  I'll ask for a review and we can merge it right in shortly.

**Comment by bryanhanson** [comment]
Completed via https://github.com/cbeleites/hyperSpec/commit/bd8a1a57ad590ff66095fa455f429d308adf45d8 Closing.
