### ISSUE TITLE
Get (mostly) rid of `make`

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#132]
**hyperSpec** currently has a very elaborate `Makefile` system. This proved to be difficult for contributors. 

One goal of the refactoring during Google Summer of Code 2020 is to arrive at a state where `Makefile`s are not or at least only hardly needed.

Changes/proposals should thus aim at reducing the complexity of the `Makefiles`.

**Comment by cbeleites** [comment]
An immediately needed "subissue" of this is to sufficiently reduce the usage of `make` to allow `devtools::build()` and `devtools::check()` to run.

**Comment by GegznaV** [comment]
Can you write down the main point, why `make` is used in **hyperSpec**?

1) To build vignettes? And if it is the only reason, we can temporarily remove vignettes and add return them back later.
2) To build data? In this scenario, we can use `usethis::use_data()` to save data in a correct format to make them distributable with **hyperSpec**. Later, we can write instructions (documentation) how these datasets could be obtained from the raw data.

What are the other reasons?

**Comment by cbeleites** [comment]
@GegznaV 

1. yes  
   -  chondro and fileio vignettes will anyways be removed during GSoC since chondro will become its own data package and the file import functions will be split into several packages dedicated each to a single file format. 
  - plotting (#136) and hyperSpec (#135) are "harmless": all they need can comparatively easily be transferred into the packages' `vignette/` directory. 
  - flu and laser need a decision: 
    - the raw data files of `flu` can easily live in the package `rawdata` (or `raw_data`) directory. They are actually shipped with the package. The data set technically is in `flu.rda`, though, which is created from the files in the raw data directory when the vignette is built. 

2. The main idea historically was to make sure vignettes and data kept in sync - even if the vignette was distributed pre-built.  So, yes, `flu`, `laser`, `barbiturates` and `paracetamol` are built from their raw data when the vignettes are built. AFAIK, we cannot have this inside the package.  
  So: #137

3. see also #129

**Comment by GegznaV** [comment]
Due to the changes in  #159, we can build a package without `make`. Is this enough to close this issue or some other changes should be made? (E.g., some more `Make` files be removed).

**Comment by eoduniyi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Is make still needed on develop branch?](https://trello.com/c/L663BJsz/98-is-make-still-needed-on-develop-branch)

**Comment by cbeleites** [comment]
No more `make` :smile:

**Comment by eoduniyi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Is make still needed on develop branch?](https://trello.com/c/L663BJsz/98-is-make-still-needed-on-develop-branch)
