### ISSUE TITLE
naming convention for package zoo

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#140]
How do we name the new packages?

- @GegznaV proposes to go short names:
  > I would prefer to have some shorter names as `hy.import`, `hy.manager`, `hy.plot`, `hyperImport`, `hyperWrangler` `hyperPlot`, etc.  

   I agree => (+3)

Does anyone have a strong opinion on 

- CamelCase (**hyperChemoBridge**) vs.
- dots (**hyperSpec.dplyr** or **hy.dplyr**) (+3) vs.
- ~~underscores (**hy_io_spc**, **hy_dplyr**)~~ not possible according to @GegznaV  

=> please edit this comment and +1 behind your choice.

Bryan: no strong opinion as to name convention, you might consider `hyS.X` (add an "S") rather than just `hy.X` so that users might see that it goes with `hyperSpec` if they are browsing around.

**Comment by eoduniyi** [comment]
I agree with @bryanhanson: I think it should be more than just `hy.X` as there is potential confusion between the hyperSpec universe and the [Hy programming language](https://en.wikipedia.org/wiki/Hy), the interesting [Hy.ly startup](https://hy.ly/our-story/), or the English phonetic abbreviation hy.

I have a preference for the following: `hyS.X`,`hySp.X` (could be confused with [this](https://hesburgh-yusko.nd.edu/about-the-program/the-hysp-model/) or [this](https://www.linkedin.com/company/china-huayang-steel-pipe-co/)), or my favorite `hySpc.X`.

```R
# Install and load hyperSpec bridge packages
install.packages("hySpc.import") # this may get installed/loaded with library(hyperSpec) as default
library(hySpc.import)
.
.
.
# Import/read Kaiser file
hySpc.import::Kaiser()
```

**Comment by bryanhanson** [comment]
`hySpc.X` is Excellent!

**Comment by GegznaV** [comment]
I'd prefer to use all non-capital letters. Of course, with RStudio's auto-complete possibilities it is not a big problem, but still... 
`hy.etc` was just an example of an idea as some functions, e.g., `hyperSpec::hy.getOption()` and `chk.hy()`, use this abbreviation.

**Comment by ximeg** [comment]
@eoduniyi I've done some legwork :) `hySpc.<X>` is a great suggestion, but I agree with Vilmantas, that lower-case would be easier to type: `hyspc.<X>`.

**Comment by ximeg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Naming convention for the package zoo](https://trello.com/c/9VY49CJS/67-naming-convention-for-the-package-zoo)

**Comment by ximeg** [comment]
Together agreed on `hySpc.<x>`  naming. The capitalization is there to be consistent with `hyperSpec`, where `S` is capitalized.

**Comment by bryanhanson** [comment]
Closing as this has been resolved.
