### ISSUE TITLE
remove leftover use of @log slot

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#141]
... in method for matrix multiplication matrix x hyperSpec object (Arith.R)

**Comment by GegznaV** [comment]
Related: #130

**Comment by bryanhanson** [comment]
Good catch @GegznaV !  This means we get to "kill 2 birds with 1 stone" if you know that saying... or perhaps you have the Lithuanian equivalent!

**Comment by GegznaV** [comment]
We have something like "shoot two rabbits in one shot"

**Comment by bryanhanson** [comment]
Perfect!  I have some rabbits getting into my garden...
