### ISSUE TITLE
Reading Witec Truematch [feature request]

### ISSUE THREAD

**Issue by b8e5n** [cbeleites/hyperSpec#142]
Here is a type of file that cannot be read with current versions of hyperSpec.
It is a simple flat file with headers, particle stats and spectrum. Multiple particles/spectra can also be found in the same file.

Example (same as shared file). The first header appears once, and the following three appear for each particle: [SpectrumHeader], [SampleMetaData], [SpectrumData]

>[WITEC_TRUEMATCH_ASCII_HEADER]
>Version = 1.0
>
>[SpectrumHeader]
>Title = Particle 916
>ExcitationWavelength = 532.200988769531
>SpectrumSize = 1024
>XDataKind = nm
>
>[SampleMetaData]
>Length = 2640.01312255859
>Width = 1492.57919311523
>Aspect Ratio = 0.565368096226994
>Num Pixels = 1126535.5
>Area = 1760211.71875
>Convex Area = 2807953.125
>Perimeter = 34951.4545096457
>Convex Perimeter = 6786.21671453118
>Feret Max = 2701.17004394531
>Feret Min = 1476.01593017578
>CE Diameter = 1497.05416315468
>Circularity = 0.134561906706767
>Convexity = 0.194161210448577
>Solidity = 0.626866489713926
>SE Volume = 1756754854.39222
>IsOversaturated = False
>RamanSignal = 0.444489509828629
>FluorescenceSignal = 191.418079663348
>
>[SpectrumData]
>528.208474329979	683
>528.344382428309	680
>528.480282838357	683.5
>528.616175566999	684.5
>528.752060621108	682
>528.887938007554	681
>529.023807733202	687

[Ex1_export_ASCII.txt](https://github.com/cbeleites/hyperSpec/files/4676431/Ex1_export_ASCII.txt)

**Comment by ximeg** [comment]
@b8e5n Thank you for sharing the example file.
> It is a simple flat file with headers, particle stats and spectrum. Multiple particles/spectra can also be found in the same file.

I suppose (and it seems to be the case here) that usually each spectrum in the file has the same wavelength axis. Do you know, is it always the case? However, the header `[SpectrumHeader]` is probably there for a reason, as it mentions the excitation wavelength and the spectrum size. So I think the import filter should return a list of `hyperSpec` objects, and it will be up to the user to `collapse` them together.

We can read the field [SampleMetaData], so that the resulting hyperSpec could have this representation:
```
hyperSpec object
   1 spectra
   X data columns
   1024 data points / spectrum
wavelength: lambda/nm [numeric] 528.2084 528.3443 ... 664.3265
data:  (1 rows x 22 columns)
   1. Title: Title [character] Particle 916
   2. ExcitationWavelength: lambda/nm [numeric] 532.200988769531
   3. Length: [numeric] 2640.01312255859
   4. Width: [numeric] 1492.57919311523
   5. AspectRatio: [numeric] 0.565368096226994
   6. NumPixels: [numeric] 1126535.5
   7. Area: [numeric] 1760211.71875
   8. ConvexArea: [numeric] 2807953.125
   9. Perimeter: [numeric] 34951.4545096457
   10. ConvexPerimeter: [numeric] 6786.21671453118
   11. FeretMax: [numeric] 2701.17004394531
   12. FeretMin: [numeric] 1476.01593017578
   13. CEDiameter: [numeric] 1497.05416315468
   14. Circularity: [numeric] 0.134561906706767
   15. Convexity: [numeric] 0.194161210448577
   16. Solidity: [numeric] 0.626866489713926
   17. SEVolume: [numeric] 1756754854.39222
   18. IsOversaturated: [boolean] False
   19. RamanSignal: [numeric] 0.444489509828629
   20. FluorescenceSignal: [numeric] 191.418079663348
   21. filename: filename [character] spectrum.txt
   22. spc: I / au.u [matrix] 683 680 ... 908.5

```

**Comment by b8e5n** [comment]
@ximeg Thanks for the quick response.
The `[SpectrumHeader]` is useful here and I believe the information should be kept. I am not sure if the spectrum data always have the same wavelength within the same file. Though I doubt that it would be the case, I would consider that it can change. I think your proposition is perfectly fine. Possibly, the collapse could be an argument when calling the read function.
Your proposition of data structure seems perfect to me. Either each category is created directly by the lines of the metadata, or the categories could be fixed for the file type. I favour the first solution as it should be more future proof.

**Comment by ximeg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Check performance of different ways to import the text data](https://trello.com/c/f0WEMFHL/72-check-performance-of-different-ways-to-import-the-text-data)

**Comment by ximeg** [comment]
Do you know, if you acquire a lot of spectra (e.g.) spectra map, are they saved into a one large file, or a bunch of individual files?

**Comment by b8e5n** [comment]
I believe there should be few thousands spectra per file at most. So it is not huge, but it is not simply few spectra. It is not a full map neither. This truematch returns 1 or 2 signals of what looks to be particles.

**Comment by cbeleites** [comment]
@eoduniyi I'd prefer a rather specific name for the package providing this functionality, e.g. **hySpc.read.txt.Witec** or **hySpc.read.Witec** (for all kinds of files produced by Witec instruments)
**hySpc.import** (as suggested on the trello card) would be a monster almost as big as **hyperSpec** before splitting off the other packages...

**Comment by eoduniyi** [comment]
Okay agreed!

**Comment by eoduniyi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [hySpc.read.Witec](https://trello.com/c/rgBeMAAK/97-hyspcreadwitec)

**Comment by cbeleites** [comment]
@eoduniyi, for other file formats that have metadata I ususally provided a parameter like `keys.meta2data` (`keys.log2data`, `keys.hdr2data`, ... for log blocks, header blocks, ... these meta data sections come under different names in different file formats) that specifies which entries of the metada should be put into extra data columns.

**Comment by ximeg** [comment]
We are going to implement support for this file format in a separate package named [hySpc.read.Witec](https://github.com/r-hyperspec/hySpc.read.Witec). The background is that in the future all file import functions would be removed from the hyperSpec itself and addressed by several separate packages. TODO for the implementation of this function is [here](https://github.com/r-hyperspec/hySpc.read.Witec/issues/1). Ideally this feature request itself should be moved there.

**Comment by GegznaV** [comment]
@cbeleites could you transfer this issue to a more appropriate repo: `r-hyperspec/hySpc.read.Witec`. I do not have permission to do so.

![image](https://user-images.githubusercontent.com/12725868/88427986-b5933e80-cdfc-11ea-9e37-ba6b94f18d7c.png)

**Comment by cbeleites** [comment]
Unfortunately, I cannot move the issue to a repository with another owner (r-hyperspec).

I'm closing this issue here since https://github.com/r-hyperspec/hySpc.read.Witec/blob/develop/R/read_txt_Witec_TrueMatch.R provides the import filter.
