### ISSUE TITLE
Replace `chondro` in the examples with fauxCell

### ISSUE THREAD

**Issue by eoduniyi** [cbeleites/hyperSpec#145]

**Comment by eoduniyi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As soon as the fauxCell synthetic data set is done, go through all examples and replace Chondro with fauxCell.](https://trello.com/c/OkUeOESw/70-as-soon-as-the-fauxcell-synthetic-data-set-is-done-go-through-all-examples-and-replace-chondro-with-fauxcell)

**Comment by GegznaV** [comment]
Omstead of totally removing examples with chondro, maybe it's reasonable to
move these examples to chondro vignette (If they are not present there).

2020 geg. 27, tr 16:56, Erick Oduniyi <notifications@github.com> rašė:

**Comment by cbeleites** [comment]
Some of them, yes. Many are actually duplicates of code in vignettes (hyperSpec, chondro, plotting).

**Comment by GegznaV** [comment]
Related: #178
