### ISSUE TITLE
Create a new GitHub organization for hyperSpec packages

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#146]
GitHub provides a possibility to create [organizations](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-organizations) – shared accounts for open source (and business) projects.  I  suggest creating an organization for the **hyperSpec** family packages, files, documentation, etc. so that people, who are interested in this project, could easily find all **hyperSpec**-related content.
My suggestion is inspired by the following organizations:

- https://github.com/tidyverse/ (for the main **tidyverse** packages)
- https://github.com/r-lib (for other **tidyverse**-related packages)
- https://github.com/mlr-org/ (for machine learning with **mlr** family packages)
- https://github.com/easystats (for "easy" statistics)

**Comment by bryanhanson** [comment]
This looks like a good idea, would we call it the "hyperSpecVerse"?

**Comment by GegznaV** [comment]
I think the name could be just "hyperspec" or "hyperSpec" (I'm not sure if it is case sensitive) or could have the same name as the main package after **hyperSpec** is split into several packages. (I prefer not to have that "verse").

**Comment by cbeleites** [comment]
I'd be in favor of hyperSpec. But: [github tells me the name is already taken](https://github.com/hyperSpec).

I do have a (so-far empty) [group on gitlab](https://gitlab.com/hyperSpec), though

**Comment by ximeg** [comment]
What about name _Chemometrix_?

**Comment by GegznaV** [comment]
"chemometrix" is also taken. 
What's about "r-hyperspec", or "hyperspec-org", or "hyperspec-proj"?

**Comment by cbeleites** [comment]
I took chemometrix :-)

**Comment by GegznaV** [comment]
Basing on the conversation last week, I did not know, that `"chemometrix"` is related to a company (and in this way is not totally neutral). So basing on this updated information, I think I'd prefer a more neutral name for the organization (I've listed my suggestions above).

**Comment by cbeleites** [comment]
I created **r-hyperspec** and invited you @all.

I propose to keep hyperSpec here until we don't need LFS any more: my understanding is that while I have some free bandwidth for LFS, the organization doesn't.

The new packages can and should have their home in https://github.com/r-hyperspec/ from now on.
