### ISSUE TITLE
Create standard categories and assign @concept and @keyword tags for automatic indexing 

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#151]
A list of objects (functions, datasets, other topics) grouped by topic (similarly as in [this table](https://gegznav.github.io/hyperSpec/articles/hyperspec.html#appendix-1-overview-of-the-functions-provided-by-package-hyperspec) in appendix 1 of `hyperSpec` vignette) could be created by `pkgdown`. This list could be automatically populated based on the documentation topics and contents of **roxygen** tags `@concept` and `@keyword`.

So I suggest standardizing function names, where possible (as documentation topic usually = function name), and adding either `@concept` or `@keyword` or both tags to documentation.  This process should be standardized, so:

- [ ]  we should decide on conventions, which keywords/concepts should be used in certain situations.
- [ ] include this information in the guidelines for contributors.

The full list of available keywords with explanation:
```r
browseURL(file.path(R.home("doc"), "KEYWORDS"), browser = "Rstudio")
```
or just keywords
```r
gtools::keywords()
```

Related links:

- https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html#other-tags
- https://pkgdown.r-lib.org/reference/build_reference.html#topic-matching

Related issues: #78, #96

**Comment by GegznaV** [comment]
I see that most of the functions in **hyperSpec** have keywords 👍

**Comment by GegznaV** [comment]
The following topics/functions potentially have missing keywords:

- [ ] as.hyperSpec
- [ ] collapse
- [ ] colSums
- [ ] count_lines
- [ ] cov,hyperSpec,missing-method
- [ ] .cluster.wavelengths
- [ ] .collapse.equal
- [ ] .fix_spc_colnames
- [ ] .read.spe.xml
- [ ] .read.spe.xml_string
- [ ] droplevels,hyperSpec-method
- [ ] empty
- [ ] guess.wavelength
- [ ] labels<-
- [ ] makeraster
- [ ] mark.dendrogram
- [ ] markpeak
- [ ] merge,hyperSpec,hyperSpec-method
- [ ] normalize01
- [ ] orderwl
- [ ] plotmat
- [ ] qplotc
- [ ] qplotmap
- [ ] legendright
- [ ] qplotmixmap
- [ ] qplotspc
- [ ] rbind.fill.matrix
- [ ] read.spc.Kaiser
- [ ] read.asc.PerkinElmer
- [ ] read.jdx
- [ ] read.spe
- [ ] read.txt.Horiba
- [ ] read.txt.Shimadzu
- [ ] rmmvnorm
- [ ] seq.hyperSpec
- [ ] spc.rubberband
- [ ] spc.smooth.spline
- [ ] spc.NA.approx
- [ ] subset
- [ ] Summary
- [ ] vanderMonde
- [ ] wc
- [ ] wl.eval
- [ ] wl
- [ ] wl2i
- [ ] wlconv

**Comment by bryanhanson** [comment]
`gtools::keywords()`

**Comment by GegznaV** [comment]
This task will be less time-consuming (and should be done) after functions are moved to appropriate **hySpe.\*** packages.

**Comment by GegznaV** [comment]
I found out that `@concept`s work better than keywords as there is functionality to list all functions/objects, that do have certain concepts. 

I did the classification of functions with `@concept`s in #225. We will see, it works. And if it does, I could describe which concepts should be used.

For now, I close this.
