### ISSUE TITLE
What do tags "ready", "blocked", etc. mean and when they should be used?

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#152]
1) What do the tags "ready" and "blocked" mean and when should they be used and when removed?

    ![image](https://user-images.githubusercontent.com/12725868/84389448-b7af8e00-abfe-11ea-99d7-0b9569ab3caf.png) ![image](https://user-images.githubusercontent.com/12725868/84389519-d150d580-abfe-11ea-9a47-17520a3d45ad.png)

2. Next, what is the difference between "proposal" and "enhancement" tags? When which of these two be used? Does "enhancement" imply that this will be implemented in the future and "proposal" that will not? Shouldn't there be any rules when "proposal" turns into something else ("enhancement", "blocked", etc.)?
![image](https://user-images.githubusercontent.com/12725868/84389850-59cf7600-abff-11ea-8601-faa33b105e19.png) ![image](https://user-images.githubusercontent.com/12725868/84390193-e5490700-abff-11ea-8cb9-defb95756058.png)

3. What is the purpose of these tags (1-4) and when should they be used:
![image](https://user-images.githubusercontent.com/12725868/84390288-ff82e500-abff-11ea-84b6-3ae110af9606.png)

May short descriptions of the tags mentioned in this issue be added? As,  e.g., ![image](https://user-images.githubusercontent.com/12725868/84390444-453fad80-ac00-11ea-8f26-3cd99057c725.png)

**Comment by ximeg** [comment]
I believe that 'Blocked' means "Cannot be started until another issue is resolved". I added the description to it. I don't know about others.

**Comment by cbeleites** [comment]
@ximeg yes, that's how I use it. 

- **proposal** can be any proposal, including proposing things like contribution guidelines.
- whereas **enhancement** means that the issue requests a new feature.  

I don't think we've ever used the tags listed under point 3 - they may have been automatically created. I deleted them.

**Comment by GegznaV** [comment]
If I understand correctly, "blocked" is converted into "ready" when the time comes ("ready" is just used to contrast that "blocked" is removed)?

**Comment by cbeleites** [comment]
@GegznaV  yes

**Comment by GegznaV** [comment]
Ok, now it's clear.
