### ISSUE TITLE
Version names standards for branches (release / master and develop)

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#155]
In the **hyperSpec** family packages, there is no convention what package versions should be used on certain branches. I suggest the following naming scheme:

- `0.0.0.9000` for unreleased packages on all branches.
- `x.x.x` for released packages (here x.x.x is major.minor.patch verion numbers) and on **`master`**/**`release`** branches.
- `x.x.x.9000` for development versions especially on **`develop`** branch. Part `9000` indicates that this is a development version and we usually do not need to use e.g. `9001`, `9002` (except in some special cases).
- On all other branches, any version numbers may be used, but before accepting them to **`develop`**, the version should be set to match the version on **`develop`**.

**Comment by bryanhanson** [comment]
Add this to `CONTRIBUTING.md`.

**Comment by ximeg** [comment]
@GegznaV Could you please post a link to the corresponding tidyverse guide that suggests this naming scheme?

**Comment by cbeleites** [comment]
Keyword list:

`gtools::keywords()`

**Comment by GegznaV** [comment]
>  Could you please post a link to the corresponding tidyverse guide that suggests this naming scheme?

- http://r-pkgs.had.co.nz/description.html#version
- http://r-pkgs.had.co.nz/release.html#release-version

**Comment by cbeleites** [comment]
commit 5d2f589 adds the `.9000` convention to CONTRIBUTING.md.
