### ISSUE TITLE
Warnings in baseline.Rmd vignette

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#157]
UPDATE: warnings are in `baseline.Rmd`

After building `baseline.Rmd` vignette, the following warnings appear:

```r
Output created: baseline.html
Warning messages:
1: In max(x@wavelength) : no non-missing arguments to max; returning -Inf
2: In min(x@wavelength) : no non-missing arguments to min; returning Inf
3: In max(x@wavelength) : no non-missing arguments to max; returning -Inf
4: In min(x@wavelength) : no non-missing arguments to min; returning Inf
```

At some point, either the warnings should be removed or it should be confirmed that they are intentional.

Related to PR #147.

**Comment by cbeleites** [comment]
@GegznaV can you confirm that you still get this warning? I tried but cannot reproduce it.

**Comment by GegznaV** [comment]
I cannot reproduce it either. Most probably it was fixed.

**Comment by GegznaV** [comment]
I attributed the warnings to the wrong vignette. They are in `baseline.Rmd` (I updated my messages above).

![image](https://user-images.githubusercontent.com/12725868/85399567-b582f300-b55f-11ea-96ff-ba4b9c3d04dd.png)
