### ISSUE TITLE
Enable Git Pages

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#158]
@cbeleites, could you, please:

1. Enable Git Pages for this repo. The source is `gh-pages` branch (there are files there https://github.com/cbeleites/hyperSpec/tree/gh-pages)
2. Add this URL for easy access: http://cbeleites.github.io/hyperSpec/dev
![image](https://user-images.githubusercontent.com/12725868/84781472-8dd7dc00-afef-11ea-9781-2b5795387ecf.png)

We will change the URL by removing `/dev` after we start using more regular version numbers.

**Comment by cbeleites** [comment]
@GegznaV  Done :)

**Comment by GegznaV** [comment]
I'm not sure why, but neither https://cbeleites.github.io/hyperSpec/ nor https://cbeleites.github.io/hyperSpec/dev still do not work 😐

**Comment by GegznaV** [comment]
Wors perfectly now 👍

**Comment by GegznaV** [comment]
@cbeleites Could you re-enable the website (Git Pages). There were issues related to links. I cleaned the `gh-pages` branch, but in the wrong way so the source of the website had reset too.

**Comment by cbeleites** [comment]
should hopefully come back now

**Comment by GegznaV** [comment]
Works again. Thanks 👍
