### ISSUE TITLE
Git-ignore NAMESPACE + build vignettes + pass automatic R-CMD-check

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#160]
Remove issues that do not allow git-ignoring the NAMESPACE file and passing automatic R-CMD-check. More details in https://github.com/cbeleites/hyperSpec/pull/153#discussion_r440037367.

Related: #159

**Comment by GegznaV** [comment]
After converting datasets into "static" ones, NAMESPACE could be `.gitignore`d (see #159). Still, I think there will be some issues after Rmd vignettes are merged (PR #147). So **do not close** this issue until PR #147 is merged or until we are sure that the vignettes will not reveal this issue again.

**Comment by GegznaV** [comment]
Bullet 3 in https://github.com/cbeleites/hyperSpec/pull/153#issuecomment-644103026 may also be relevant:

> the error looks as if we're missing an `@import`. I'll have to look into this.

**Comment by GegznaV** [comment]
Related: https://github.com/cbeleites/hyperSpec/issues/163#issuecomment-645980725

**Comment by cbeleites** [comment]
I'll close this now:

- the vignettes build fine on the CI, and
- we decided for #163 that NAMESPACE & man/*.Rd will stay ignored.
