### ISSUE TITLE
Rd warning due to oversimplified linking syntax in documentation

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#161]
While building the package, I get many Rd warnings. A single warning looks like this one:

```
Rd warning: D:/Dokumentai/R/hyperSpec/hyperSpec/man/Arith.Rd:94: file link 'Math' in package 'hyperSpec' does not exist and so has been treated as a topic
```

<details>

The warnings include:

- [ ] `./hyperSpec/man/apply.Rd:59: file link 'Math' in package 'methods' <...>`
- [ ] `./hyperSpec/man/Arith.Rd:94: file link 'Math' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/asdataframe.Rd:94: file link 'as.matrix' in package 'base' <...>`
- [ ] `./hyperSpec/man/asdataframe.Rd:98: file link 'melt' in package 'reshape' <...>`
- [ ] `./hyperSpec/man/bind.Rd:98: file link 'rbind2' in package 'methods' <...>`
- [ ] `./hyperSpec/man/bind.Rd:99: file link 'rbind' in package 'base' <...>`
- [ ] `./hyperSpec/man/colSums.Rd:31: file link 'colMeans' in package 'base' <...>`
- [ ] `./hyperSpec/man/colSums.Rd:32: file link 'rowMeans' in package 'base' <...>`
- [ ] `./hyperSpec/man/colSums.Rd:32: file link 'rowSums' in package 'base' <...>`
- [ ] `./hyperSpec/man/Comparison.Rd:76: file link 'isTRUE' in package 'base' <...>`
- [ ] `./hyperSpec/man/Comparison.Rd:106: file link 'sweep-methods' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/Comparison.Rd:114: file link 'Math' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/Comparison.Rd:117: file link 'isTRUE' in package 'base' <...>`
- [ ] `./hyperSpec/man/cov.Rd:22: file link 'cov' in package 'stats' <...>`
- [ ] `./hyperSpec/man/cov.Rd:46: file link 'cov' in package 'stats' <...>`
- [ ] `./hyperSpec/man/decomposition.Rd:72: file link 'plotmap' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/dim.Rd:47: file link 'ncol' in package 'base' <...>`
- [ ] `./hyperSpec/man/dimnames.Rd:30: file link 'rownames' in package 'base' <...>`
- [ ] `./hyperSpec/man/dimnames.Rd:33: file link 'rownames' in package 'base' <...>`
- [ ] `./hyperSpec/man/dimnames.Rd:51: file link 'rownames' in package 'base' <...>`
- [ ] `./hyperSpec/man/dollarnames.Rd:23: file link '.DollarNames' in package 'utils' <...>`
- [ ] `./hyperSpec/man/droplevels-hyperSpec-method.Rd:12: file link 'droplevels.data.frame' in package 'base' <...>`
- [ ] `./hyperSpec/man/levelplot.Rd:91: file link 'panel.levelplot.raster' in package 'lattice' <...>`
- [ ] `./hyperSpec/man/levelplot.Rd:109: file link 'panel.identify' in package 'lattice' <...>`
- [ ] `./hyperSpec/man/math.Rd:81: file link 'Math' in package 'base' <...>`
- [ ] `./hyperSpec/man/math.Rd:85: file link 'Summary' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/merge.Rd:22: file link 'merge.data.frame' in package 'base' <...>`
- [ ] `./hyperSpec/man/palettes.Rd:21: file link 'rainbow' in package 'grDevices' <...>`
- [ ] `./hyperSpec/man/palettes.Rd:22: file link 'colorRampPalette' in package 'grDevices' <...>`
- [ ] `./hyperSpec/man/palettes.Rd:43: file link 'rainbow' in package 'grDevices' <...>`
- [ ] `./hyperSpec/man/pearson.dist.Rd:33: file link 'as.dist' in package 'stats' <...>`
- [ ] `./hyperSpec/man/plot.Rd:92: file link 'plot' in package 'graphics' <...>`
- [ ] `./hyperSpec/man/plotspc.Rd:88: file link 'plot' in package 'graphics' <...>`
- [ ] `./hyperSpec/man/plotspc.Rd:185: file link 'plot' in package 'graphics' <...>`
- [ ] `./hyperSpec/man/plotspc.Rd:246: file link 'plot' in package 'graphics' <...>`
- [ ] `./hyperSpec/man/qplotmixmap.Rd:12: file link 'qmixlegend' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/qplotmixmap.Rd:13: file link 'qmixtile' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/qplotmixmap.Rd:31: file link 'qmixtile' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/qplotspc.Rd:22: file link 'geom_line' in package 'ggplot2' <...>`
- [ ] `./hyperSpec/man/qplotspc.Rd:24: file link 'geom_line' in package 'ggplot2' <...>`
- [ ] `./hyperSpec/man/qplotspc.Rd:29: file link 'geom_line' in package 'ggplot2' <...>`
- [ ] `./hyperSpec/man/qplotspc.Rd:61: file link 'geom_line' in package 'ggplot2' <...>`
- [ ] `./hyperSpec/man/rbind.fill.Rd:58: file link 'rbind' in package 'base' <...>`
- [ ] `./hyperSpec/man/read.asc.PerkinElmer.Rd:12: file link 'read.txt.long' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/read.ENVI.Rd:158: file link 'read.ENVI' in package 'caTools' <...>`
- [ ] `./hyperSpec/man/read.ENVI.Rd:164: file link 'read.ENVI' in package 'caTools' <...>`
- [ ] `./hyperSpec/man/read.txt.Horiba.Rd:33: file link 'read.txt.wide' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/read.txt.Renishaw.Rd:55: file link 'gzfile' in package 'base' <...>`
- [ ] `./hyperSpec/man/rmmvnorm.Rd:31: file link 'rmvnorm' in package 'mvtnorm' <...>`
- [ ] `./hyperSpec/man/rmmvnorm.Rd:48: file link 'rmvnorm' in package 'mvtnorm' <...>`
- [ ] `./hyperSpec/man/rmmvnorm.Rd:50: file link 'pooled.cov' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/scale.Rd:17: file link 'as.matrix' in package 'base' <...>`
- [ ] `./hyperSpec/man/scale.Rd:22: file link 'as.matrix' in package 'base' <...>`
- [ ] `./hyperSpec/man/seq.Rd:15: file link 'seq.int' in package 'base' <...>`
- [ ] `./hyperSpec/man/seq.Rd:31: file link 'seq_along' in package 'base' <...>`
- [ ] `./hyperSpec/man/show.Rd:72: file link 'as.character' in package 'base' <...>`
- [ ] `./hyperSpec/man/spc-rubberband.Rd:43: file link 'spc.fit.poly' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/spc-rubberband.Rd:43: file link 'spc.fit.poly.below' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/spc-rubberband.Rd:47: file link 'hy.setOptions' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/spc-spline.Rd:40: file link 'spc.loess' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/summary.Rd:71: file link 'isTRUE' in package 'base' <...>`
- [ ] `./hyperSpec/man/textio.Rd:111: file link 'R.matlab' in package 'R.matlab' <...>`
- [ ] `./hyperSpec/man/textio.Rd:119: file link 'read.spc' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/textio.Rd:135: file link 'R.matlab' in package 'R.matlab' <...>`
- [ ] `./hyperSpec/man/textio.Rd:139: file link 'R.matlab' in package 'R.matlab' <...>`
- [ ] `./hyperSpec/man/textio.Rd:147: file link 'read.spc' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/textio.Rd:162: file link 'R.matlab' in package 'R.matlab' <...>`
- [ ] `./hyperSpec/man/textio.Rd:219: file link 'R.matlab' in package 'R.matlab' <...>`
- [ ] `./hyperSpec/man/textio.Rd:223: file link 'read.spc' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/unittests.Rd:13: file link 'testthat' in package 'testthat' <...>`
- [ ] `./hyperSpec/man/wl.Rd:19: file link 'signif' in package 'base' <...>`
- [ ] `./hyperSpec/man/wl.Rd:47: file link 'spc.loess' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/wl.Rd:48: file link 'spc.bin' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/wl.Rd:67: file link 'signif' in package 'base' <...>`
- [ ] `./hyperSpec/man/wl.Rd:71: file link 'spc.loess' in package 'hyperSpec' <...>`
- [ ] `./hyperSpec/man/wl.Rd:73: file link 'spc.bin' in package 'hyperSpec' <...>`

Here `<...>` stands for "does not exist and so has been treated as a topic".

</details>

The following links, the essence of the warnings and the ways to solve the issue are explained:

- [How do I resolve Rd warning “missing file link” when building packages in RStudio?](https://stackoverflow.com/questions/48430093/how-do-i-resolve-rd-warning-missing-file-link-when-building-packages-in-rstudi)
- https://roxygen2.r-lib.org/articles/markdown.html#links

***

You may think that this is not very important but may also have noticed that there are two R-CMD-checks in CI workflow: one for R-devel and one for other R versions. The reason is that these Rd warnings become into R-CMD-check warnings for the R-devel version warnings re not treated as errors. (For all other R versions, warnings are treated as errors.)

![image](https://user-images.githubusercontent.com/12725868/84816125-b0ccb500-b01c-11ea-9f5a-07c2c8517e63.png)

**Comment by bryanhanson** [comment]
I believe this may be fixed in the latest release for `roxygen2`.

**Comment by GegznaV** [comment]
When I build **hyperSpec** with **roxygen2** `v 7.1.1` on Windows, I do not get the warnings anymore. Thus I close the issue.
