### ISSUE TITLE
Note: man/*.Rd and NAMESPACE files are required for easy installation form GitHub

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#163]
After `Make` is removed, if we want the users of **hyperSpec** to have the possibility to install the development version of the package as easy as:
```r
if (!require(remotes)) {install.packages("remotes")}
remotes::install_github("cbeleites/hyperSpec/hyperSpec", ref = "develop")
```
without any additional configuration and _(I think)_ without installation of Git and Git-LFS, which are needed for developers only (regularly, R packages provide this kind of possibility), the `.Rd` documentation files should be present in Git repository's `man` folder. I.e., they should not be Git-ignored. And if they are, the result is:

![image](https://user-images.githubusercontent.com/12725868/84889494-9f79bc00-b0a1-11ea-8dc7-4b0b4813ba1e.png)

But maybe there is an easy workaround for this issue?

***

**P.S.** The code above should work is after PR #159 and/or #162 are merged into `develop` branch. Meanwhile, you may try code (before the branch `enable_codecov` is deleted):
```r
remotes::install_github("GegznaV/hyperSpec/hyperSpec", ref = "enable_codecov")
```
***
**P.P.S.** I haven't tried, what is the influence of Git-ignored `NAMESPACE` file in this kind of installation.

**Comment by GegznaV** [comment]
Here comes the answer about the `NAMESPACE` file. I tried to install package with vignettes from GitHub:

```r
remotes::install_github(
    "cbeleites/hyperSpec/hyperSpec", ref = "feature/vignettes-in-rmd", 
    dependencies = TRUE, 
    build_vignettes = TRUE, 
    force = TRUE
)
```

The result was:

```r
√  checking for file 'C:\Users\ViG\AppData\Local\Temp\RtmpmQDDff\remotes5eb477b74b66\cbeleites-hyperSpec-b0cdda1\hyperSpec/DESCRIPTION' (435ms)
-  preparing 'hyperSpec':
√  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes
         -----------------------------------
-  installing *source* package 'hyperSpec' ...
   ** using staged installation
   ERROR: a 'NAMESPACE' file is required
-  removing 'C:/Users/ViG/AppData/Local/Temp/Rtmp2t5HTg/Rinst337c339a5cf5/hyperSpec'
         -----------------------------------
   ERROR: package installation failed
```
***
> ERROR: a 'NAMESPACE' file **is required**
***

**Comment by cbeleites** [comment]
I think it's best if we discuss & decide Monday on the video call:

- on the one hand, it's better not to track redundant information
- on the other hand, it's good to allow easy installation of the development version.

---
Some more thoughts:

- https://github.com/r-lib/devtools/issues/397 https://github.com/r-lib/devtools/issues/523
- We may refer people to the dev .tar.gz/.zip files generated as artifact in the continuous integration
- `DESCRIPTION` will always need to be tracked, but it's `Collate` field is already auto-generated

**Comment by bryanhanson** [comment]
Decided in video meeting 22 June to use the latest develop build.

**Comment by cbeleites** [comment]
Possibly even `.zip` file for windows users (available either via github action artifacts or appveyor)

**Comment by cbeleites** [comment]
Decided in video meeting 2020-07-16 to put the development builds to  https://r-hyperspec/hySpc.pkgs .
Users can install them via `install.packages(repos = c("r-hyperspec.github.io/hySpc.pkgs/", getOption("repos"))`.
