### ISSUE TITLE
Match the names of the package and the main vignette

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#168]
There are advantages in `pkgdown` if the names of the package and the main vignette match. Now they do not as "hyperSpec" and "hyperspec" is not the same.

> By default, the top navigation bar (the "navbar") will contain links to:  
>
> - [...]
> - "Get Started", if you have an article with the same name as the package  (e.g., `vignettes/pkgdown.Rmd`).

https://pkgdown.r-lib.org/reference/build_site.html#yaml-config-navbar

**Comment by cbeleites** [comment]
There are also advantages to users - who don't need to think where to spell "hyperSpec" which way.

**Comment by GegznaV** [comment]
There are issues to automatically link vignette `hyperSpec.Rmd` correctly in `pkgdown` website due to capital letters. (Click on "Get started" in  cbeleites.github.io/hyperSpec/dev/ and you'll see)

Current page: cbeleites.github.io/hyperSpec/dev/articles/hyperspec.html
Should be: cbeleites.github.io/hyperSpec/dev/articles/hyperspec.html

Thus now I think that #170 should be reverted.

**Comment by GegznaV** [comment]
This is already a part of `develop` branch via #147
