### ISSUE TITLE
Update CITATION to take info from DESCRIPTION automatically

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#169]
To have the most up-to-date citation information for **hyperSpec** (and to make it easier to maintain),  `inst/CITATION` file should be updated to take information from `DESCRIPTION` file. 
See the code in `packageStartupMessage()` in `.onAttach()` in [`zzz.R`](https://github.com/cbeleites/hyperSpec/blob/develop/hyperSpec/R/zzz.R) as an example of automation.

**Comment by ximeg** [comment]
@GegznaV Isn't it resolved now by your commit bd9bd021ecc8? Can this issue be closed?

**Comment by GegznaV** [comment]
No, it is a `packageStartupMessage`, not a citation. 
https://github.com/cbeleites/hyperSpec/blob/develop/hyperSpec/inst/CITATION

**Comment by ximeg** [comment]
Okay, I see your point now
