### ISSUE TITLE
What is the difference: GC,GC-MS vs. GCxGC-MS?

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#172]
What is the difference between `GC,GC-MS` and `GCxGC-MS` spectroscopies? Or is it the same just abbreviation has a typo?

---
Note: `fileio--fileformats.txt`

**Comment by bryanhanson** [comment]
No typos.  GC is "gas chromatography", MS is "mass spectrometry".  GC-MS is a so-called hyphenated technique in which GC does the separation and MS does the detection.  GCxGC-MS has two different GC columns for separation followed by MS detection... Does that help?

**Comment by GegznaV** [comment]
https://github.com/cbeleites/hyperSpec/blob/043a86f7ea49944d6c39f0f342701d693aeb2ef6/hyperSpec/vignettes/fileio--fileformats.txt 
So if there is no error in this file, I close the issue. Otherwise, it should be reopened.
