### ISSUE TITLE
Code from fileio.Rmd vignette for unit tests

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#174]
This is the code from `fileio.Rmd` which could be used to create unit tests:  [fileio-for-unit-tests.zip](https://github.com/cbeleites/hyperSpec/files/4807099/fileio-for-unit-tests.zip) as stated in https://github.com/cbeleites/hyperSpec/issues/79#issue-343402745:

>  untangle historic mix with unit tests into vignette and unit tests

**Comment by cbeleites** [comment]
Thanks. I assign @eoduniyi  so he has a notification since he'll need this starting with **hySpc.read.Witec**.

**Comment by eoduniyi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [hySpc.read.Witec](https://trello.com/c/rgBeMAAK/97-hyspcreadwitec)

**Comment by eoduniyi** [comment]
I believe @cbeleites has taken care of this, so going to close this now.

**Comment by cbeleites** [comment]
No, I have not yet taken care of this.

**Comment by eoduniyi** [comment]
Oh oops, I will get on it ASAP.

**Comment by GegznaV** [comment]
**This discussion was moved and continues as:**

- https://github.com/r-hyperspec/hySpc.read.txt/issues/79
