### ISSUE TITLE
Are GitHub issue templates needed?

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#175]
I wonder if we need GitHub Issue templates for bug reports, feature requests, questions, etc., in order to get standardized information in issues?

**Comment by ximeg** [comment]
To be honest, I don't think it is really necessary. This makes most sense if you regularly get bug reports and people struggle with writing them well. But it wouldn't hurt to have a template.

**Comment by GegznaV** [comment]
When I was writing this issue, I was thinking about feature requests which ask to implement to read some file formats. But this functionality will go to a new package (or several of them).
