### ISSUE TITLE
Should sample have an argument index like seq does?

### ISSUE THREAD

**Issue by bryanhanson** [cbeleites/hyperSpec#177]
It would seem more logical and consistent for the `sample` method to have an `index = T/F` argument like the `seq` method does.  If so, `isample` could be eliminated.

This came up while reviewing `hyperSpec.Rmd`.

**Comment by cbeleites** [comment]
I'm certainly for consistency. :+1: 

But I'm not sure whether it is better to have

- `isample()` and `iseq()` or
- `sample(index = TRUE)` and `seq(index = TRUE)`

Opinions?

**Comment by bryanhanson** [comment]
I like the 2nd option, as it is fewer functions overall.

**Comment by cbeleites** [comment]
We'll need to deprecate `isample()` then.

**Comment by bryanhanson** [comment]
And remove `isample()` from `hyperSpec.Rmd` and possibly other places.

**Comment by cbeleites** [comment]
@eoduniyi would you take care of this?

**Comment by eoduniyi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #177](https://trello.com/c/DOBg8hDc/104-issue-177)

**Comment by bryanhanson** [comment]
@eoduniyi Let me know when you do this as there is code in `hyperSpec.Rmd` that I will need to change.

**Comment by eoduniyi** [comment]
> @eoduniyi Let me know when you do this as there is code in `hyperSpec.Rmd` that I will need to change.

@bryanhanson I don't think I ever did this...

**Comment by bryanhanson** [comment]
@eoduniyi That is true.  But prioritize the things we discussed last night.  Do this if you need a change of task.  Working those vignettes benefits from frequent breaks, at least for me.

**Comment by GegznaV** [comment]
Issue moved and reopened as:
- https://github.com/r-hyperspec/hyperSpec/issues/17
