### ISSUE TITLE
Rename fauxCell into faux_cell

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#178]
In order to follow guidelines in section [2.1 Object names](https://style.tidyverse.org/syntax.html#object-names) in the Tidyverse style guide, I recommend renaming `fauxCell ` (camel case) into **`faux_cell`** (snake case).

P.S., if we'd agree on this, I could do it really quickly.

**Comment by bryanhanson** [comment]
This is fine with me, but I'm not a close follower of naming conventions.

**Comment by cbeleites** [comment]
Fine with me, too.
