### ISSUE TITLE
Replacement Function Argument Handling and Error Messages

### ISSUE THREAD

**Issue by bryanhanson** [cbeleites/hyperSpec#183]
Playing further from the novice perspective, here are several operations that seem to me like they should either work or give a `hyperSpec`-generated error message (as opposed to what `R` provides by default, which is classically cryptic).  It may be that I am not groking the triple indexing used with `hyperSpec`.

```
# Case 1 -- can't replace an element of the j index with a value that seems reasonable
flu[, "c", ] <- 1:6 # unhelpful error message
# this does work:
flu$c <- 1:6
```

```
# Case 2 -- can't replace a single spectrum with a value that seems reasonable
flu[1,,] <- 1:181 # unhelpful error message
# one gets the same error message if you pass a vector of the wrong length
# should probably get a different error messaage about replacement lengths
```

I may have other questions after these!

**Comment by cbeleites** [comment]
Case 1: good catch. That was a bug. 

Fixing also leads to case 2 "working", with a more sensible warning: 

```
> flu[1,,] <- 1:181
Warning message:
In matrix(value, n, p) :
  data length [181] is not a sub-multiple or multiple of the number of columns [3]
```
What happens here is that `flu[1,,] <- value` replaces a complete row of the `@data` data.frame. With more values than columns, the first 3 values only are used and the spectra matrix becomes a flat 1 spectrum, `$filename[1]` is 2, and `$c[1]` is 3.

To replace values of the spectra matrix without touching the extra data column, use `[[<-`: 
```
flu[[1,,]] <- 1 : 181
```

**Comment by cbeleites** [comment]
The bug itself is fixed now, but I'll leave the issue open for now since the 2nd aspect of this is overhauling 

- [ ] the .Rd documentation
- [ ] the description in vignette hyperSpec

**Comment by bryanhanson** [comment]
Yes, keep open.  I noticed some other infelicities in the documentation but I need to study more carefully (this week).

**Comment by bryanhanson** [comment]
Fixed documentation in `Extract.Rd` and in `hyperSpec.Rmd`.  See https://github.com/cbeleites/hyperSpec/commit/c90221f3b4a13d8c69a451224e973c900fc5fc30
