### ISSUE TITLE
When could hyperSpec version be changed into v0.100.0?

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#192]
Could we change the version number to v0.100.0? In this way, we would begin using more conventional version numbers (#155). Maybe some additional issues should be solved before doing this?

Before releasing **hyperSpec** 1.0.0, may we also release (at least on GitHub) some minor versions or patches, e.g., v0.100.0, v0.100.1, etc.?

**Comment by ximeg** [comment]
I agree that it makes sense to release what we have. The state is more or less stable, the package can be built and passes all checks.

**Comment by bryanhanson** [comment]
We should hold off on a release until I have finished revising `hyperSpec.Rmd` and Claudia has a chance to review it.  I will probably be done by the end of the week.

**Comment by cbeleites** [comment]
- From my side, go ahead doing a version bump to 0.100 anytime.
- We will not be able to relase hyperSpec to CRAN before the chondro data package works since it is too big with the data sets in `data/` now.

**Comment by GegznaV** [comment]
See also https://github.com/cbeleites/hyperSpec/pull/203#issuecomment-654119381 (related to NEWS file).
