### ISSUE TITLE
Missing section (cross-referene) in fileio.Rmd 

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#193]
![image](https://user-images.githubusercontent.com/12725868/85351175-c570e780-b50b-11ea-9129-9579672c72cb.png)

***
Related:
- r-hyperspec/hySpc.read.txt#21
- #267

**Comment by GegznaV** [comment]
May be fixed by writing a section or correcting data in file https://github.com/cbeleites/hyperSpec/blob/develop/hyperSpec/vignettes/fileio--fileformats.txt

**Comment by cbeleites** [comment]
I think this can best be resolved when the **hySpc.read.\*** packages are done.
