### ISSUE TITLE
Codecov does not report the results for hyperSpec

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#194]
Codecov results are not reported for **hyperSpec**.

![image](https://user-images.githubusercontent.com/12725868/85351656-f1409d00-b50c-11ea-9384-01a324692db4.png)

The settings we use 
https://github.com/cbeleites/hyperSpec/blob/e0312e96e767e6d8da4a7ff31b4435b4aa8a505a/.github/workflows/R-CMD-check.yaml#L129
worked fine on the other project of mine. Of course, additional settings could be used:
https://github.com/codecov/codecov-action

But maybe the admin of this repo should grant some permissions. I'm not sure.

**Comment by cbeleites** [comment]
I enabled the project on codecov. 
Not sure why it still doesn't work since github action documentation says no token is needed for public projects.

**Comment by GegznaV** [comment]
Now reports are uploaded to Codecov, but coverage in `.r` files cannot be viewed as the package is in `./hyperSpec` and not in `.`, e.g., what happens if I try to open file `./hyperSpec/R/cov.R` in https://codecov.io/gh/cbeleites/hyperSpec/tree/develop/R:

![image](https://user-images.githubusercontent.com/12725868/86983288-2cd99900-c194-11ea-8ac4-af0ff57a2136.png)


Paths are relative and should be fixed in `codecov.yml`. More details at https://docs.codecov.io/docs/fixing-paths

**Comment by GegznaV** [comment]
Commit cd37d39 finally solved the issue.
