### ISSUE TITLE
On Vignette Style standards

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#196]
In [CONTRIBUTING.md](https://github.com/cbeleites/hyperSpec/blob/develop/CONTRIBUTING.md#vignette-style-and-standards), it is written:

1. > Figure and Table should be capitalized when mentioned in text, e.g. Figure 1.

     Does this also mean, that `Fig.` can be used as well?

2. > NEED TO DISCUSS: formatting of code blocks. Could use tidy = TRUE as one option.

    I think this point can be removed, as an analogical option is already implemented in c26f2b804fbf383701acb0ae06ed0d0175cedae8

**Comment by bryanhanson** [comment]
By executive decision I will not allow "Fig."  and I will remove the formatting "need to discuss" section.

Closed via https://github.com/cbeleites/hyperSpec/commit/aa631708dafce883e747947806edde9e63c2bb0d
