### ISSUE TITLE
Update installation instructions in README.md

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#198]
Could a note be added tho this section (see the picture below)  of `README.md`, that the documentation of the package will not be installed in this way and the user should read instructions in the next section?

![image](https://user-images.githubusercontent.com/12725868/85428420-da8a5c80-b585-11ea-996e-575d8f6cf626.png)

**Comment by ximeg** [comment]
Sure, go on and add it 😀

**Comment by GegznaV** [comment]
I think a more comprehensive update should be done to README after **hySpc.pkgs** is made functional.

**Comment by bryanhanson** [comment]
To be clear, `hySpc.pkgs` is fully functional, but at this time only serves `hySpc.read.Witec`.
