### ISSUE TITLE
Reach code coverage of at least 60%

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#207]
Currently, code coverage by unit tests is quite low, around 30%. [![Codecov test coverage](https://codecov.io/gh/cbeleites/hyperSpec/branch/develop/graph/badge.svg)](https://codecov.io/gh/cbeleites/hyperSpec?branch=develop). I think, at least 60% should be reached.

So this issue should be closed only after 60% or even better code coverage is reached.

@eoduniyi is it ok, that I assign this to you?

**Comment by GegznaV** [comment]
Resources:

- Unit tests for graphical functions: https://github.com/r-lib/vdiffr (extension of **testthat**)

**Comment by eoduniyi** [comment]
Yes! I need to practice writing unittest

**Comment by GegznaV** [comment]
Related issue: #174. 

May you start by wrapping the code in #174 into unit tests, @eoduniyi?

**Comment by eoduniyi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Start making sure code coverage is at least 60% for hyperSpec](https://trello.com/c/0zFrxBkZ/116-start-making-sure-code-coverage-is-at-least-60-for-hyperspec)

**Comment by cbeleites** [comment]
Also, right now the existing tests for `read.*()` are skipped via `skip_if_not_fileio_available()`. I think they are best enabled again once these functions are in their respective new packages.

**Comment by GegznaV** [comment]
I'm closing this as some other more specific tasks on how to improve unit tests should be created in separate issues.
