### ISSUE TITLE
Rename functions to match the Tidyverse style

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#208]
In the **tidyverse** style guide, sections on object names and function names ([2.1 Object names](https://style.tidyverse.org/syntax.html#object-names); [3.1 Naming](https://style.tidyverse.org/functions.html#naming); very short sections, so you can read them now) suggest that function names contain only letters, digits, and underscores. Dots `.` are advised to be used only for S3 methods. Capital letters should be avoided too. 

Some of the function names in **hyperSpec** do not comply with these style rules even though `CONTRIBUTING.md` states that 

>- This project adheres to the Tidyverse styleguide.

I see an inconsistency here.

Some of the possible suggestions what could be done:

1) To rename some/most of the function names (except additional methods for **base** or other packages, e.g., `as.data.frame.hyperSpec()`), that names do not comply with the **tidyverse** style and have two versions of function names for backward compatibility.
2) The same as (1) but deprecate the names that do not comply with the style.
3) Update `CONTRIBUTING.md` that all **new** functions must comply with the **tidyverse** style, but the package has functions that do not in order to avoid breaking changes.
4) _/ other options are also possible /_

***

My personal position is to rename at least some of the functions. Especially, `spc.*` and `normalize.*` series. 
(The `read.*` and `write.*` series might also be renamed). And now (before splitting **hyperSpec** into separate packages and releasing `1.0.0`, as major release means that breaking changes are introduced.

![image](https://user-images.githubusercontent.com/12725868/87300423-73255400-c516-11ea-873d-4a5cd67910d5.png)

![image](https://user-images.githubusercontent.com/12725868/87302582-4ffca380-c51a-11ea-9095-3f876df0b37a.png)

***

P.S. If there is a question about **styler** package, it only does those changes that do not break the code. I.e., it does not rename functions. Thus, this issue is not related to **styler**.

**Comment by GegznaV** [comment]
The functions can be renamed, but the old names should be properly deprecated.

**Comment by cbeleites** [comment]
I see the tidyverse style as a *recommendation*, i.e. nothing to follow blindly. 

- I'm fine with naming new functions in snake_case.
- OTOH, we will anyways have a mix of naming styles since we need to adhere to the spelling of any function we import/overload. Thus, I don't see any urgency in renaming functions for the sake of having some more snake_case.  
- The `read.*()` functions can be renamed to `read_*()` when moving them into their new packages, though.
- As we discussed in the video meeting on 2020-07-20, function names refering to manufacturers/companies, software, standards or abbreviations should use the common/proper spelling of those rather than lower casing it.

**Comment by GegznaV** [comment]
I'm going to rename some functions by following these principles:

- use Tidyverse style, where possible;
- use a common prefix for certain types of functions (when applicable; in some cases this requres rearanging function name parts):
    + prefix **`hy_`** for utility functions;
    + prefix **`spc_`** for functions that operate on `@spc` (whet it is needed to stress that calculation is made on `@spc`, in most cases `spc_` is not used).
    + prefix **`wl_`** for wavelength-related functions.
    + prefix **`palette_`** for functions, that create collor palettes.

**Comment by GegznaV** [comment]
I'm closing this issue as there were more specific issues (listed above) opened.
