### ISSUE TITLE
Shorten the output of show() method

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#209]
**NOTE:** This post was updated on 2020-07-15 by changing function names as `show()` is responsible for implicit printing, and not `print()` as I thought before. 
***
Currently, the methods `print()` and `show()` give the same results. Usually, I work with spectroscopic datasets with many _extra data_ columns. If (accidental) printing of `hyperSpec` object occurs, the output clutters the whole console in my case.

I think, for `show()`, the shorter output would be better. I suggest:

![image](https://user-images.githubusercontent.com/12725868/87535248-dd1d3500-c69f-11ea-88bb-d4b671dc4232.png)
**Fig. 1.**

Either `print()` (or `summary()`) could result in:

![image](https://user-images.githubusercontent.com/12725868/87535324-f9b96d00-c69f-11ea-949c-b2f5d3a0f916.png)
**Fig. 2.**

Would it be acceptable to have these changes? If not, could we have another function, that results in the output displayed in  Fig. 1?

**Comment by ximeg** [comment]
I like this idea :+1:
