### ISSUE TITLE
Modify the output of print()

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#210]
I suggest adapting some features\ideas of `tibble:::print.tbl()` and/or `tibble::glimpse()` to make the result of `show()` more compact:

1. Fit the output of each line into the width of the console window (as `glimpse()`) does. Maybe, some minimal number of characters could be used, as summary of `hyperSpec` object is less compact than the summary of `data.frame`
2. _(maybe)_ Add possibility not to print some column names if there are too many of them (as in `tibble:::print.tbl()`).
3. _(maybe)_ Use abbreviations of data types as **tidyverse** packages do, e.g., `<fct>` instead of `[factor]`, `<chr>` instead of `[character]`, etc. (e.g., in the output of `glimpse()`)
4.  _(maybe)_ Use colors in output (e.g., if RStudio is used, as in `tibble:::print.tbl()` and `tibble::glimpse()`).
5. Not to print a label, if it coincides with the column name.

**Comment by ximeg** [comment]
Nice idea, I actually have already done this long time ago using `glimpse` when I was working with spectra that contain a lot of metadata. The only downside is that glimpse does not show the last value in the vector, as hyperSpec currently does.

**Comment by ximeg** [comment]
I've found that piece of my old code that uses `glimpse`, modified the source and opened a PR. The result would be like this:

```R
faux_cell
#> hyperSpec object
#>    875 spectra
#>    4 data columns
#>    300 data points / spectrum
#> wavelength: Delta * tilde(nu)/cm^-1 [numeric] 602 606 ... 1798 
#> data:  (875 rows x 4 columns)
#> $ x      <dbl> -11.55, -10.55, -9.55, -8.55, -7.55, -6.55, -5.55, -4.55, -3.5…
#> $ y      <dbl> -4.77, -4.77, -4.77, -4.77, -4.77, -4.77, -4.77, -4.77, -4.77,…
#> $ region <fct> matrix, matrix, matrix, matrix, matrix, matrix, matrix, matrix…
#> $ spc    <dbl[,300]> <matrix[26 x 300]>
```

**Comment by GegznaV** [comment]
In #211, the defaults of `print()` give the same result as `show()`. Maybe we can modify `print()` method to give the same result as in #213? O maybe we could introduce `glimpse()` method for **hyperSpec**?

**Comment by GegznaV** [comment]
We decided not to use dependency on **`tibble`** package.
