### ISSUE TITLE
Should .fix_spc_colnames() be a hidden function?

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#233]
An exported function function `.fix_spc_colnames()` is hidden (stasts with dot `.`? Shouldn't we rename it to make it into a regular (not hidden) function?

**Comment by cbeleites** [comment]
I vote for keeping this hidden. 

- It is a helper function that users should not need to call themselves, but
- that packages that extend **hyperSpec** may need/want to call/import. IIRC, we use it in **hySpc.dplyr**

**Comment by GegznaV** [comment]
As the function is exported, it must have the documentation accessible to users. The same could be said about `.DolarNames()`. I was working on the documentation (#225) yesterday, so these questions arose automatically, as the functions looked different than  the others.
