### ISSUE TITLE
Does method .DollarNames(<hyperSpec>) have to be exported?

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#234]
Method `.DollarNames(<hyperSpec>)` seems to be an _extremely_ internal function that is not necessary to be accessed directly by users. So why is it exported? Shouldn't we change this?

**Comment by cbeleites** [comment]
`.DollarNames()` is how R's tab completion finds out which extra data columns exist. It needs to be exported to work.

So while users don't call it *directly*, it is probably one of the most frequently used functions in **hyperSpec**.
