### ISSUE TITLE
Do we expect this when we plot the map of faux_cell?

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#235]
@bryanhanson, do we expect to see this when we plot `faux_cell`? Shouldn't we see some larger structures like in `chondro`? It seems a lot of noise here. Isn't something wrong here?
```r
library(hyperSpec)
plotmap(faux_cell)
```
![image](https://user-images.githubusercontent.com/12725868/88801340-38781880-d1b2-11ea-8a9d-d355441a3236.png)

**Comment by bryanhanson** [comment]
Looks odd to me.  Where is is from?

**Comment by GegznaV** [comment]
I added code to reproduce the plot. I'm wondering, if something isn't lost in the code.

**Comment by GegznaV** [comment]
I mean, isn't something lost in the code that generate the `faux_cell`?

**Comment by GegznaV** [comment]
For reference:
```r
library(hyperSpec)
plotmap(chondro)
```
![image](https://user-images.githubusercontent.com/12725868/88803118-ade4e880-d1b4-11ea-9bf9-2eede68f5cc9.png)

**Comment by cbeleites** [comment]
`plotmap(spc)` plots the average intensity of each spectrum in `spc`. 

- for `chondro`, we have mostly continuous changes here (I'd suspect them to be related to a slight curvature of the sample and resulting differences in focusing).
- for `faux_cell`, the changes are driven by the differences between baselines, which are random and uncorrelated between the spectra.

So yes, the plot is correct.

**Comment by GegznaV** [comment]
OK, the following code gives:
```r
mapcols <- c(cell = "aquamarine", matrix = "aliceblue", nucleus = "dodgerblue")
plotmap(faux_cell, region ~ x * y, col.regions = mapcols)
```
![image](https://user-images.githubusercontent.com/12725868/88803555-4d09e000-d1b5-11ea-8f7d-360aa03b34f9.png)

But this means, that `chondro` could not be replaced with `faux_cell` as easily as just by changing the dataset's name.

**Comment by bryanhanson** [comment]
Good point @GegznaV .

**Comment by GegznaV** [comment]
On the other hand, doesn't `region ~ x * y` show that values of `region` are mapped and not the values of spectroscopic signals? Doesn't it indicate, that the spectroscopic signal has no (or little) information on the parts of the cell?

**Comment by bryanhanson** [comment]
@GegznaV you are right about how the map is created, it assumes the regions are known in advance.  So probably we need a better or an additional example. Claudia noted above that `plotmap(faux_cell[,,1200])` shows the structure (to a degree).

**Comment by GegznaV** [comment]
1200 is good enough. In the examples of `plotmat`, 1003 is indicated. So, it's better to use 1200 there.

Thank you, @bryanhanson

**Comment by GegznaV** [comment]
The "secret" wavenumbers that make sense in the map are 800, 1200, 1500 1/cm.
```r
qplotmixmap(faux_cell[, , c(800, 1200, 1500)],
  purecol = c(matrix = "red", cell = "green", nucleus = "blue")
)
```
![image](https://user-images.githubusercontent.com/12725868/88810440-01a7ff80-d1be-11ea-9ada-8cba9012d30c.png)
