### ISSUE TITLE
Refactoring: move anonymous functions into hidden functions

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#238]
There are still quite a lot of calls to `setMethod()` in **hyperSpec** that use anonymous functions, e.g.

```r
setMethod("colSums", signature = signature(x = "hyperSpec"), function(x, na.rm = TRUE, ..., label.spc) {
  result <- colSums(x@data$spc, na.rm = na.rm, ...)
  if (is.matrix(result) && ncol(result) != nwl(x) && nrow(result) == nwl(x)) {
    result <- t(result)
  }

  decomposition(x, result, scores = FALSE, label.spc = label.spc)
})
```

Moving these anonymous functions into hidden functions, e.g. 

```r
.colSums <-  function(x, na.rm = TRUE, ..., label.spc) {
  result <- colSums(x@data$spc, na.rm = na.rm, ...)
  if (is.matrix(result) && ncol(result) != nwl(x) && nrow(result) == nwl(x)) {
    result <- t(result)
  }

  decomposition(x, result, scores = FALSE, label.spc = label.spc)
}

setMethod("colSums", signature = signature(x = "hyperSpec"), .colSums)
```
would make the code easier to debug and also to unit test (#230). Possibly also easier to read

---

Marked as low priority since this is not a change that a user would notice, so it is not necessary to do this before the 1.0 milestone

**Comment by GegznaV** [comment]
I did this in #225 for some functions for which I created unit tests. The most relevant commits have the same structure of commit messages "Update the way unit tests are attached in _some-file-name_". @cbeleites, please, review the PR.
