### ISSUE TITLE
Drat for `develop` branch of hyperSpec

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#243]
@bryanhanson, could you temporarily enable functionality so that the **hyperSpec** version from `develop` branch could be installed via **drat** repo? Or is to difficult to implement and we should use some other solution?

It is needed to test if new *hySpc** packages work smoothly with the development version of **hyperSpec**. Currently, those packages use CRAN version of **hyperSpec** and this can hide some issues.

**Comment by bryanhanson** [comment]
I can set this up sometime today.

**Comment by GegznaV** [comment]
It would be nice. Just I recommend not touching current files in `.github/` dir, but just adding a new file. Even if some functionality overlaps.

**Comment by bryanhanson** [comment]
That's my plan.

**Comment by bryanhanson** [comment]
@cbeleites Can you grant me admin access to `hyperSpec` or set up a  secret token there and tell me its name?  This is needed to automatically deploy `develop` versions of various packages into `hySpc.pkgs`.  Thanks.

**Comment by bryanhanson** [comment]
Working via https://github.com/cbeleites/hyperSpec/commit/97ed08c7c6a902736ecd08ac5ac0625559daa1d1
