### ISSUE TITLE
Move all appropriate functions to hySpc.read.txt package

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#263]
1. Copy all functions that read data from text/ASCII files to package **hySpc.read.txt**
2. In **hyperSpec**, add concept `#' @concept moved to hySpc.read.txt` to the documentation of each function that is copied to **hySpc.read.txt**
    - **NOTE:** functions should not be removed from **hyperSpec** for now (for backward compatibility), just the concept should be added.
3. In `NEWS.md`, the list of copied functions should be added. It should be stated, that "these functions were moved to **hySpc.read.txt** and will be removed from **hyperSpec** in the next release"

We will solve other related issues later.

Related: r-hyperspec/hySpc.read.txt#22

***

**UPDATE**

Make sure that the following functions are moved to **hySpc.read.txt** (there are file name and functions in that file)

+ [x] read.txt.Horiba.R
    - [x] `read.txt.Horiba`
    - [x] `read.txt.Horiba.xy`
    - [x] `read.txt.Horiba.t`
+ [x] read.txt.long.R
    - [x] `read.txt.long`
+ [x] read.txt.Renishaw.R
    - [x] `read.txt.Renishaw`
    - [x] `read.zip.Renishaw`
+ [x] read.txt.Shimadzu.R
    - [x] `read.txt.Shimadzu`
+ [x] read.txt.wide.R
    - [x] `read.txt.wide`
+ [x] read.txt.Witec.R
    - [x] `read.txt.Witec`
    - [x] `read.dat.Witec`
    - [x] `read.txt.Witec.Graph`
+  ~~wc.R~~
    - ~~`wc`~~
+ [x] count_lines.R
    - [x] `count_lines`
+ [x] read.asc.Andor.R
    - [x] `read.asc.Andor`
+ [x] read.asc.PerkinElmer.R
    - [x] `read.asc.PerkinElmer`

You can find these files and functions here: [move-to--hySpc-read-txt.zip](https://github.com/cbeleites/hyperSpec/files/5093315/move-to--hySpc-read-txt.zip)

The following files (and functions in them) should not be moved to **hySpc.read.txt** as the functions are used not only in **hySpc.read.txt** but also elsewhere:

- [x] fileio.optional.R

**Comment by eoduniyi** [comment]
This is the same as [issue #22](https://github.com/r-hyperspec/hySpc.read.txt/issues/22) in `hypSpc.read.txt`

**Comment by GegznaV** [comment]
@eoduniyi I updated the description of this issue above. I noticed that the list in r-hyperspec/hySpc.read.txt#22 was to short and not accurate enough so I created a new list (see above). Please, check if all functions in the list above are moved to **hySpc.read.txt**. One function should not be moved.

**Comment by cbeleites** [comment]
@GegznaV thank you for compiling the list. I removed `wc()` since it is already (soft) deprecated. 
It is not used any more: I fixed the documentation in `hySpc.read.txt::read_txt_Renishaw()` and `hyperSpec::read.txt.Renishaw()`.

**Comment by eoduniyi** [comment]
This issue was closed by PR # 26 from `hypSpc.read.txt`

**Comment by GegznaV** [comment]
You may link the issues in other repos by adding full repo name (with organization/author name) before issue number r-hyperspec/hySpc.read.txt#26
