### ISSUE TITLE
Use title case in section names of vignettes

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#268]
@eoduniyi Please, go through all the vignettes and make sure that all section titles (start with `#`, `##`, `###` etc.) use proper title case. Will you do this?

**Comment by eoduniyi** [comment]
@GegznaV I will gladly do this.

**Comment by GegznaV** [comment]
@eoduniyi Can you take time to solve this issue now (or in a period of a few days)? As there are vignettes in several *hySpc* packages, all of them should be checked. Changes should go to a separate branch which will be merged via pull request.


Code that may help:

```r
library(tidyverse)

# Get paths to vignettes
v_path <- fs::dir_ls(regexp = "(?i)[.]Rmd$", recurse = TRUE)
v_path

# Extract lines that start with `#`
i <- 1
v_path[i] %>% 
  readr::read_lines() %>% 
  stringr::str_extract("^#.*") %>%
  na.omit() %>% 
  writeLines()
```

You have to change `i` to select the file of interest and the code lists all the lines that start with `#`. It's a quick way to see if there are any title-related issues in a file. Just note that the lines that start with `#` are either Rmd section titles or R code comments.
You should also use an appropriate working directory.

**Comment by eoduniyi** [comment]
Dear @GegznaV, 

I'm still making my way through the vignettes. I have still yet to utilize your code snippet, but I agree, I think it's going to be helpful. Currently, I have had a few problems, which I've tried to note [here](https://storage.googleapis.com/work_bucket_4141/hyperSpec/hyperSpec/issues/hyperSpec_issue_268.pdf).

I should say, these notes (documentation and questions) are mostly for me to help keep track of my progress.

**Comment by eoduniyi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue #268](https://trello.com/c/s2PFtWs5/150-issue-268)

**Comment by GegznaV** [comment]
@eoduniyi, have you at least partially solved this issue? I cannot find the branch dedicated to solving this issue.

**Comment by eoduniyi** [comment]
> @eoduniyi, have you at least partially solved this issue? I cannot find the branch dedicated to solving this issue.

Yes. I will do my best to wrap this issue up later tonight CST.  The branch is called "knitr-vignettes-header-fix"
![Screen Shot 2021-02-16 at 12 58 18 PM](https://user-images.githubusercontent.com/31193655/108109043-05ff1180-7057-11eb-9fe4-830530ca92c9.png)

**Comment by GegznaV** [comment]
OK, I see. I was confused, as it does not contain the number of this issue. I expected something like `fix/268`, `fix-268`, `feature/268`, or `268-` at the beginning of the branch name.

**Comment by GegznaV** [comment]
@eoduniyi, can I expect your PR before 2021-02-23?

**Comment by eoduniyi** [comment]
> @eoduniyi, can I expect your PR before 2021-02-23?

Yes.

**Comment by eoduniyi** [comment]
Using the code snippets you outlined above, all the section names look good to me:
```R
library(magrittr)
library(dplyr)
# Get paths to vignettes
v_path <- fs::dir_ls(regexp = "(?i)[.]Rmd$", recurse = TRUE)
v_path
```

```
Vignettes/flu/flu.Rmd                                         hyperSpec.Rcheck/00_pkg_src/hyperSpec/inst/doc/baseline.Rmd   
hyperSpec.Rcheck/00_pkg_src/hyperSpec/inst/doc/fileio.Rmd     hyperSpec.Rcheck/00_pkg_src/hyperSpec/inst/doc/flu.Rmd        
hyperSpec.Rcheck/00_pkg_src/hyperSpec/inst/doc/hyperSpec.Rmd  hyperSpec.Rcheck/00_pkg_src/hyperSpec/inst/doc/laser.Rmd      
hyperSpec.Rcheck/00_pkg_src/hyperSpec/inst/doc/plotting.Rmd   hyperSpec.Rcheck/00_pkg_src/hyperSpec/vignettes/baseline.Rmd  
hyperSpec.Rcheck/00_pkg_src/hyperSpec/vignettes/fileio.Rmd    hyperSpec.Rcheck/00_pkg_src/hyperSpec/vignettes/flu.Rmd       
hyperSpec.Rcheck/00_pkg_src/hyperSpec/vignettes/hyperSpec.Rmd hyperSpec.Rcheck/00_pkg_src/hyperSpec/vignettes/laser.Rmd     
hyperSpec.Rcheck/00_pkg_src/hyperSpec/vignettes/plotting.Rmd  hyperSpec.Rcheck/hyperSpec/doc/baseline.Rmd                   
hyperSpec.Rcheck/hyperSpec/doc/fileio.Rmd                     hyperSpec.Rcheck/hyperSpec/doc/flu.Rmd                        
hyperSpec.Rcheck/hyperSpec/doc/hyperSpec.Rmd                  hyperSpec.Rcheck/hyperSpec/doc/laser.Rmd                      
hyperSpec.Rcheck/hyperSpec/doc/plotting.Rmd 
```

For example, 
```R
# Extract lines that start with `#`
i <- 1 # Vignettes/flu/flu.Rmd     
v_path[i] %>% 
  readr::read_lines() %>% 
  stringr::str_extract("^#.*") %>%
  na.omit() %>% 
  writeLines()
``` 

```
# Writing an Import Function
# Adding further Data Columns
# Dropping data columns
# Linear Calibration
# Session Info
```

@GegznaV, Is there a particular `.Rmd` or set of `.Rmd` files you want me to take a look at (?) 🤔

**Comment by GegznaV** [comment]
I think, there was something wrong with communication as the issue could be solved without any automatic tools.
