### ISSUE TITLE
plotting vignette

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#27]
ggplot2 examples 
- map with hexagonal grid
- `qplotmixmap`

**Comment by GegznaV** [comment]
@cbeleites, if this issue is still relevant, close it here and reopen in https://github.com/r-hyperspec/hySpc.ggplot2/issues

Otherwise, just close this one.

**Comment by GegznaV** [comment]
@cbeleites, is this issue still relevant? If **yes**, please, reopen it in https://github.com/r-hyperspec/hySpc.ggplot2/issues
