### ISSUE TITLE
Submission to CRAN: Don't use R-reference, use R_reference

### ISSUE THREAD

**Issue by bryanhanson** [cbeleites/hyperSpec#275]
When submitting my package `ChemoSpec` to CRAN, I ran into a very obscure `pandoc-citeproc` issue that occurs on the CRAN check farm Debian machine. I think it arises from that machine using slightly out-dated software, but of course there's no discussing that with CRAN.

The solution, which is relevant to `hyperSpec` vignettes, is to use this sort of incantation:

```
knitr::write_bib(c("knitr", "mclust", "baseline", "hyperSpec"), file = "manuals.bib", prefix = "R_")
```
Note the last argument overrides the default `R-` which is what causes the problem.

For another CRAN submission issue see #259 This will also apply to any package with a vignette.

**Comment by Ayushsunny** [comment]
Hello @GegznaV sir So I have to start working on this issue? 
can you explain a bit more that what's the exact issue and what changes do I have to make?

**Comment by GegznaV** [comment]
@bryanhanson, could you take care of this?

**Comment by bryanhanson** [comment]
Will do!

**Comment by bryanhanson** [comment]
Closing here, same issue opened over at https://github.com/r-hyperspec/r-hyperspec.github.io/issues/19
