### ISSUE TITLE
What is the right package for `write` functions?

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#277]
The `read*()` functions will be moved to their own packages. And what is the future of `write*()` functions, that currently exist in **hypseSpec**?

**Comment by GegznaV** [comment]
As we are not going to support many output formats, I think, these functions should live in **hyperSpec**.

**Comment by eoduniyi** [comment]
I like `hySpc.write.*`

**Comment by cbeleites** [comment]
There are only 2 such export functions, `write.txt.long()` and `write.txt.wide()`. I think they can stay in **hyperSpec**. 
The question is then, should the corresponding `read.*()` functions stay in **hyperSpec** to provide minimal import/export capabilities without requiring the user to install further packages?

**Comment by eoduniyi** [comment]
@cbeleites I think the functions should stay in `hyperSpec` for the point you mentioned. It reminds me of how companies sell a "comprehensive" base model for users, but also make "modules" that can be purchased and attached to increase or widen the scope of functionality of the base model. Although the `hyperSpec` ecosystem is open source, so no purchase necessary...only `install.packages("hySpc.*")`

**Comment by GegznaV** [comment]
OK, then, talking about `read.txt.long()`,  `read.txt.wide()`, `write.txt.long()`, and  `write.txt.wide()`, let's rename the functions to match the *tidyverse* style and keep them in the main **`hyperSpec`** package.
