### ISSUE TITLE
Problem reading large area scan (raman) with read.spc

### ISSUE THREAD

**Issue by pablovgd** [cbeleites/hyperSpec#286]
Hi all

Recently I encountered some problems when reading .spc files of large area scans with the function read.spc().  Reading .spc files of single spectrum .spc files works fine, but multiple spectra large area scans don't seem to work. 
I get the following error:

```
> read.spc('LAS pseudotsuga 40x.spc')
Error in if (hdr$fzinc == 0) hdr$fzinc = subhdr$subnext - subhdr$subtime : 
  missing value where TRUE/FALSE needed
```

Strange thing is that it only happens with files I export from the program WITec Project Four. Even stranger is that other .spc files of large area scans exported by the same program by my tutor are working just fine. 
Any idea how to fix this error? 
I'll add the .spc to this post as well. 
[LAS pseudotsuga 40x.zip](https://github.com/cbeleites/hyperSpec/files/5428190/LAS.pseudotsuga.40x.zip)

Thanks in advance!

Kind regards
Pablo

**Comment by eoduniyi** [comment]
Hi @pablovgd 👋

Sorry to hear you're having some difficulties. Have you tried/looked into [`hySpc.read.txt`](https://github.com/r-hyperspec/hySpc.read.txt)? If not, please take a look at the GitHub documentation and try installing it, as I believe it's a good avenue for you to try. 

In the meantime, I will be taking a closer look at your problem/file 👁️

**Comment by GegznaV** [comment]
Closing in favor to `r-hyperspec/hySpc.read.spc#2`
