### ISSUE TITLE
Add possibility to create hyperSpec object without spectra

### ISSUE THREAD

**Issue by galaxismad** [cbeleites/hyperSpec#288]
In addition to issues #287 and #283, it would be great to have the opportunity to initialize hyperSpec objects without spectra, meaning only wavelength axis is given during initialization, but no spectral intensities are given.

**Comment by galaxismad** [comment]
It can be done quite easily with the following statement:

`new("hyperSpec", wavelength = 1:100, matrix(NA, ncol = 100, nrow = 0))`

More intuitive would be:

`new("hyperSpec", wavelength = 1:100, spc = NULL)`

**Comment by GegznaV** [comment]
The issue is fixed in #292. Let's wait if @cbeleites approves my suggestions.
