### ISSUE TITLE
Creating hyperSpec object without wavelengths

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#296]
This is the "transpose" of issue #288: creating a hyperSpec object where the spectra do not (yet) exist. 

Suggested:

```r
new("hyperSpec", data = data.frame(c = 1:5))
```

this works:

```r
new("hyperSpec",
     wavelength = numeric(0),
     spc = matrix(NA_real_, ncol = 0, nrow = 5), 
     data = data.frame(c = 1:5)
)
```

**Comment by GegznaV** [comment]
I've solved this on my PC, just did not want to create too many PR before the current ones are reviewed.

**Comment by GegznaV** [comment]
To clarify, I have suggestion for:

```r
new("hyperSpec", data = data.frame(c = 1:5))
```

**Comment by GegznaV** [comment]
I ran unit tests on my implementation and understood that the issue is more complex than it seemed at first glance.

Currently, the official solution to this issue in **hyperSpec** is to use `as.hyperSpec()`:

```r
as.hyperSpec(data.frame(c = 1:5))
```

```r
as.hyperSpec(as.matrix(data.frame(c = 1:5)))
```

```r
as.hyperSpec(matrix(1:5))
```

**Comment by GegznaV** [comment]
Issue reopened as https://github.com/r-hyperspec/hyperSpec/issues/99
