### ISSUE TITLE
Use more consistent signature for methods of as.hyperSpec()

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#297]
Currently, each method of `as.hyperSpec()` uses its own order, default values and number of arguments:

```r
.as.hyperSpec.matrix <- function(X, wl = guess.wavelength(colnames(X)), ...)

.as.hyperSpec.data.frame <- function(X, spc = NULL, wl = guess.wavelength(spc), labels = attr(X, "labels"), ...)

.as.hyperSpec.hyperSpec <- function(X)
```

This makes it more difficult to use in other functions as each case should be addressed separately.
My suggestions would be to:

- use `NULL` for the default values in the signature and perform calculations or real initial values inside the methods;
- use consistent order of arguments;
- rename argument  `wl` into the name that will be suggested in #90.

May also be related: https://github.com/cbeleites/hyperSpec/issues/144#issuecomment-750338337

**Comment by cbeleites** [comment]
This is a very good point. +1

**Comment by GegznaV** [comment]
Moved and reopened as:
- https://github.com/r-hyperspec/hyperSpec/issues/16
