### ISSUE TITLE
Rename functions (1): palette_

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#299]
This issue complements https://github.com/cbeleites/hyperSpec/issues/208#issuecomment-684085699.

In the development version of **`hyperSpec`**, I found 4 functions/objects that define color palettes.
I suggest using consistent naming (prefix **`palette_`**) for all palette-related objects:

Status | Current name          | Suggested name
:---:|----------------------|-------------------
Done in  #313  | ~~`CB7`~~                 |  ~~`palette_colorblind`~~
✔️ | `matlab.dark.palette` | `palette_matlab_dark`
✔️ | `matlab.palette`      | `palette_matlab`
✔️ | `alois.palette`       | `palette_alois`

**Comment by bryanhanson** [comment]
`CB7` is color-blind-friendly so when renaming it should probably get a more descriptive name, perhaps something like `palette_colorblind`.

I'm in favor of these changes.

**Comment by cbeleites** [comment]
Sounds good to me.
I think this could be a good first issue, since it will get a newcomer through the deprecation etc. steps.

@GegznaV, if you agree, please tag it good-first-issue.

**Comment by GegznaV** [comment]
I'll review later if it can be a `good-first-issue`

**Comment by GegznaV** [comment]
Remove `NOT DONE` in `NEWS.md` after the remaining functions are properly renamed and the old ones are deprecated.
The rows to fix in `NEWS.md`:

     Deprecated function     | New (replacement) function       | Related issues
    -------------------------|-------------------------------   | ----------------
     `matlab.dark.palette`   | `palette_matlab_dark`            |  #208, #299 NOT DONE
     `matlab.palette`        | `palette_matlab`                 |  #208, #299 NOT DONE
     `alois.palette`         | `palette_alois`                  |  #208, #299 NOT DONE
