### ISSUE TITLE
Rename functions (3): spc_ 

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#301]
This issue complements https://github.com/cbeleites/hyperSpec/issues/208#issuecomment-684085699.

I suggest renaming these functions to match *tidyverse* style better:

**Table 1**

Status | Current name          | Suggested name
:---:| ----------------------|-------------------
✔️ | `spc.NA.approx`       | `spc_na_approx`
✔️ | `spc.bin`             | `spc_bin`
✔️ | `spc.fit.poly`        | `spc_fit_poly`
✔️ | `spc.fit.poly.below`  | `spc_fit_poly_below`
✔️ | `spc.loess`           | `spc_loess`
✔️ | `spc.smooth.spline`   | `spc_smooth_spline`
✔️ | `spc.rubberband`      | `spc_rubberband`

And this one to have a more consistent name with other **`spc_`** functions:

**Table 2**

Current name          | Suggested name | Comment
----------------------|------------------- |---------------------
`.fix_spc_colnames`   | `.spc_fix_colnames` | Closes #233

**Comment by bryanhanson** [comment]
I support this proposal.
