### ISSUE TITLE
Rename functions (4):  helpers

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#302]
This issue complements https://github.com/cbeleites/hyperSpec/issues/208#issuecomment-684085699.

Current name          | Suggested name    | Comment
----------------------|-------------------|-------------------------------------
`mergeextra`       | `merge_data` | More consistent naming with field `@data`.
`.fileio.optional` | `.spc_io_postprocess_optional` | Name that  conveys the essence of function better may is needed.

**Comment by bryanhanson** [comment]
`merge_data` sounds good; the other one I'm not familiar with so I will let others decide.
