### ISSUE TITLE
Rename functions (5): decomposition

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#303]
This issue complements https://github.com/cbeleites/hyperSpec/issues/208#issuecomment-684085699.

These functions may also be renamed. But extension or modification of functionality should also be introduced.

Current name          | Suggested name    | Comment | Note
----------------------|-------------------|------------------------------------- |:--:
`decomposition`       | `as.hyperSpec(<matrix>)`, `as_hyperSpec(<matrix>)`<br>`scores2hyperSpec()`<br>`loadings2hyperSpec()` | Function can not only renamed bu also redefined as a method of  `as.hyperSpec()`, `as_hyperSpec()`. See discussion in #144. Related #289 | This issue moved to https://github.com/r-hyperspec/hyperSpec/issues/55
`chk.hy`             | `is.hyperSpec()`, `is_hyperSpec()` | **1.** May include the functionality of `validObject()` as well. <br>**2.** To keep current functionality (failure in case of non-`hyperSpec` object), argument `fail = TRUE` may be added. Default should be `fail = FALSE` to return `FALSE`.  | Solved in https://github.com/r-hyperspec/hyperSpec/pull/35

**Comment by bryanhanson** [comment]
Regarding `chk.hy` also take a look at #130 and the cross-references there-in.  I think all these concerns can be fixed at once.

Regarding `decomposition` I authored #144 so I agree this should be renamed.

**Comment by GegznaV** [comment]
This discussion moved and reopen as:
- https://github.com/r-hyperspec/hyperSpec/issues/55
