### ISSUE TITLE
Documention of plotc uses a non-documented argument

### ISSUE THREAD

**Issue by bryanhanson** [cbeleites/hyperSpec#304]
I noticed while looking at `plotspc` vs `plotc` that the documentation [here](https://cbeleites.github.io/hyperSpec/dev/reference/decomposition.html) uses in the example an argument `groups` that is not mentioned in the signature.  I think it actually passes through to lattice via `...` but the documentation says `...` is not used.  Needs investigation to verify.

**Comment by cbeleites** [comment]
@bryanhanson could you give some more details what you are missing?

`? plotc()` has:

```
...	further arguments to xyplot.
```

(`decomposition()` doesn't use its `...` argument, its documentation is correct about that. I included it in order to allow the function easily to become generic in case that's needed somewhere)

**Comment by bryanhanson** [comment]
OK, I see now that I was seeing `plotc()` in the example in `decomposition` and I was mixed up because the `...` in the documentation was about `decomposition` not `plotc`.  I should pay better attention!
