### ISSUE TITLE
GHA raises 403 for R release (4.0.4)

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#307]
Currently, I faced an issue related to GHA and R devel when GHA is unable to install the R release (4.0.4). Currently, it touches #306 and #211. I opened a question here https://community.rstudio.com/t/r-lib-actions-setup-r-results-in-403-on-gha/96253
***
**UPDATE**
The issue is Linux-related. So I'll temporarily set `4.0.3` to be used explicitly instead of `release` GHA CI on Linux. After the issue is fixed upstream,  `4.0.3` should be set back to `release`.

**Comment by GegznaV** [comment]
This may be related to the fact that R 4.0.4 was released on 2021-02-15.
![image](https://user-images.githubusercontent.com/12725868/108074445-ddd0dc00-7071-11eb-874b-b2877e655449.png)

**Comment by bryanhanson** [comment]
If you use twitter follow @githubstatus They have had a lot of problems with GHA lately so you might run into random outtages too.d

**Comment by GegznaV** [comment]
Related: https://github.com/rstudio/r-builds/issues/89

**Comment by GegznaV** [comment]
The issue is Linux-related. So I'll temporarily set `4.0.3` to be used explicitly instead of `release` GHA CI on Linux (ce29ef2)
