### ISSUE TITLE
Can we get rid of these git branches?

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#308]
Currently, there are several branches in this repo I'm not familiar with (despite the fact that I updated some of them):

- [x] `ErickGSoC`
- [x] bugfix/285-new-testthat-version
- [x] `knitr-vignettes-header-fix`
- [x] `knitr-vignettes`
- [x] `test-write`

Can we delete them?

**Comment by eoduniyi** [comment]
@GegznaV, the `ErickGSoC` can be removed. I'm working on issue #268 in the `knitr-vignettes-header-fix` branch

**Comment by GegznaV** [comment]
Thanks, Erick.

**Comment by GegznaV** [comment]
I removed `ErickGSoC`

**Comment by cbeleites** [comment]
- I removed the testthat bugfix
- `knitr-vignettes` could go but for @eoduniyi 's commit in December - not sure whether that need to be moved/picked somewhere else first?

**Comment by eoduniyi** [comment]
> * I removed `bugfix/285-new-testthat-version`
> * `knitr-vignettes` could go but for @eoduniyi 's commit in December - not sure whether that need to be moved/picked somewhere else first?

@cbeleites, both the `knitr-vignettes` and the `knitr-vignettes-header-fix` can be deleted.

**Comment by GegznaV** [comment]
@sangttruong should the branch `test-write` be deleted or merged into `develop`? If it should be merged, please, create PR and reference to this issue.

**Comment by cbeleites** [comment]
done during online meeting
