### ISSUE TITLE
incorrect spe test file dimension 

### ISSUE THREAD

**Issue by sangttruong** [cbeleites/hyperSpec#319]
The blut1.spe file doesn't work because its ydim = 0, and ydim is used to set the dimention of another matrix (hence the function throws an error). read_spe() works just fine on spe_format_3.0.spe.

**Comment by sangttruong** [comment]
@cbeleites

**Comment by sangttruong** [comment]
Reassign in r-hperspec/hySpc.read.spe

**Comment by cbeleites** [comment]
This should be in https://github.com/r-hyperspec/hySpc.read.spe/issues/1
