### ISSUE TITLE
rbind unexpected behaviour

### ISSUE THREAD

**Issue by KrzysztofBanas** [cbeleites/hyperSpec#32]
Combining two hyperspec objects with **rbind** does not work when joining bigger to smaller (in terms number of spectra) object

> Error in rbind(deparse.level, ...) : replacement has length zero 

In other order (smaller to bigger) works OK. 
**collapse** works in both cases correctly.

**Comment by cbeleites** [comment]
Hi  Krzysztof,

could you add a minimal example of the issue? I tried with the `flu` object and added a bunch of unit tests that should catch your problem, but 

```r
  test_that("flu", {
    expect_equal (rbind (flu [ 1],  flu [-1]),  flu,              check.attributes = FALSE)
    expect_equal (rbind (flu [-1],  flu [ 1]),  flu [c (2:6, 1)], check.attributes = FALSE)
    expect_equal (rbind (flu [1:2], flu [3:6]), flu,              check.attributes = FALSE)
  })

  test_that("empty objects", {
    expect_equal (rbind (flu [FALSE], flu [0]), flu [0], check.attributes = FALSE)
    expect_equal (rbind (flu [FALSE], flu [1]), flu [1], check.attributes = FALSE)
    expect_equal (rbind (flu [1], flu [0]), flu [1], check.attributes = FALSE)
    expect_equal (rbind (flu [0], flu [1]), flu [1], check.attributes = FALSE)
  })
```
all work for me.

**Comment by KrzysztofBanas** [comment]
Probably is not minimal (sorry) (not) working example but I have no experience in this :-)
Most likely I did something wrongly with data loading or pre-processing but I can't pinpoint it.
[testsmall.txt](https://github.com/cbeleites/hyperSpec/files/707321/testsmall.txt)
[testbig.txt](https://github.com/cbeleites/hyperSpec/files/707322/testbig.txt)


data loaded by read.csv
`file01 <- read.csv("D:/testbig.txt")`
dataset with wavenumbers in the first column and spectra in subsequent columns
```
spc <- t(file01[, 2:ncol(file01)])
wavenumber <- file01[, 1]
d1 <- data.frame(colnames(file01[2:ncol(file01)]))
colnames(d1)<-"Compound"
```
create hyperSpec object
`a1= new ("hyperSpec", wavelength = wavenumber, spc = spc, data=d1)`
smoothing
`a1s <- spc.loess (a1, c(seq (600, 4000, 2))) `
cutting
`a1sc_big<-a1s[,,c(3000~2800,1800~750)]`

adding one spectrum
`file02 <- read.csv("D:/2016_09_HAIRS_FTIR/testsmall.txt")`
dataset with wavenumbers in the first column and spectrum second column

```
spc <- t(file02[, 2:ncol(file02)])
wavenumber <- file02[, 1]
d2 <- data.frame(colnames(file02[2:ncol(file02)]))
colnames(d2)<-"Compound"
```
create hyperSpec object
`a2= new ("hyperSpec", wavelength = wavenumber, spc = spc, data=d2)`
smoothing
`a2s <- spc.loess (a2, c(seq (600, 4000, 2))) `
cutting
`a2sc_small<-a2s[,,c(3000~2800,1800~750)]`

`a1sc_big`

> hyperSpec object
>    11 spectra
>    2 data columns
>    627 data points / spectrum
> wavelength:  [numeric] 3000 2998 ... 750 
> data:  (11 rows x 2 columns)
>    1. Compound:  [factor] S.01 S.02 ... S.11 
>    2. spc:  [matrix627] 0.18197887 0.03187705 ... 0.008714847 

`a2sc_small`

> hyperSpec object
>    1 spectra
>    2 data columns
>    627 data points / spectrum
> wavelength:  [numeric] 3000 2998 ... 750 
> data:  (1 rows x 2 columns)
>    1. Compound:  [factor] S.00 
>    2. spc:  [matrix627] -0.2329656 -0.2174209 ... 0.1914024 

#combine together

**#not working**
`c1<-rbind(a1sc_big,a2sc_small)`

> Error in rbind(deparse.level, ...) : replacement has length zero

**#working**
```
c2<-rbind(a2sc_small,a1sc_big)
c2
```

> hyperSpec object
>    12 spectra
>    2 data columns
>    627 data points / spectrum
> wavelength:  [numeric] 3000 2998 ... 750 
> data:  (12 rows x 2 columns)
>    1. Compound:  [factor] S.00 S.01 ... S.11 
>    2. spc:  [matrix627] -0.2329656 0.1819789 ... 0.008714847 

```
c3<-collapse(a1sc_big,a2sc_small)
c3
```

> hyperSpec object
>    12 spectra
>    2 data columns
>    627 data points / spectrum
> wavelength:  [numeric] 3000 2998 ... 750 
> data:  (12 rows x 2 columns)
>    1. Compound:  [factor] S.01 S.02 ... S.00 
>    2. spc:  [matrix627] 0.18197887 0.03187705 ... 0.1914024 


```
c4<-collapse(a2sc_small,a1sc_big)
c4
```

> hyperSpec object
>    12 spectra
>    2 data columns
>    627 data points / spectrum
> wavelength:  [numeric] 3000 2998 ... 750 
> data:  (12 rows x 2 columns)
>    1. Compound:  [factor] S.00 S.01 ... S.11 
>    2. spc:  [matrix627] -0.2329656 0.1819789 ... 0.0087148

**Comment by cbeleites** [comment]
Turns out the problem is in `base::rbind.data.frame` and the fact that one of your objects has rownames for the spectra matrix and the other doesn't. 

```r
> rownames (a1sc_big@data$spc)
 [1] "S.01" "S.02" "S.03" "S.04" "S.05" "S.06" "S.07" "S.08" "S.09" "S.10" "S.11"
> rownames (a2sc_small@data$spc)
NULL
> rownames (rbind (a2sc_small@data, a1sc_big@data)$spc)
 [1] NA     "S.01" "S.02" "S.03" "S.04" "S.05" "S.06" "S.07" "S.08" "S.09" "S.10" "S.11"
> rbind (a1sc_big@data, a2sc_small@data)
Fehler in rbind(deparse.level, ...) : Ersetzung hat Länge 0
```

**Comment by KrzysztofBanas** [comment]
As I suspected It was my mistake not in your code :-)
Thanks for your help. I think it's time to close this issue.

**Comment by cbeleites** [comment]
@KrzysztofBanas, 
would you be willing to discuss the issue with the R developers on the R-devel mailing list (see https://www.r-project.org/bugs.html)? I suspect you really found a bug. 

Here's a minimal example of the situation:

```r
m <- matrix (1:12, 3)

dfm <- data.frame (c = 1 : 3, m = I (m))
str (dfm)

m.names <- m
rownames (m.names) <- letters [1:3]
dfm.names <- data.frame (c = 1 : 3, m = I (m.names))
str (dfm.names)

rbind (m, m.names)
rbind (m.names, m)

rbind (dfm, dfm.names)
rbind (dfm.names, dfm)

rbind (dfm, dfm.names)$m
```

**Comment by bryanhanson** [comment]
I think that's a good idea.

**Comment by KrzysztofBanas** [comment]
Great, thanks.
I'll do it.
