### ISSUE TITLE
Update CI workflow for Linux

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#322]
GH actions issues this warning:
![image](https://user-images.githubusercontent.com/12725868/122041143-4ee68d00-cde1-11eb-9d4e-7f9f2500fb13.png)

> **Annotations**
>
> 1 warning
> 
> Insert package (drat) : .github#L1
>
> The ubuntu-16.04 environment is deprecated and will be removed on September 20, 2021. Migrate to ubuntu-latest instead. For more details see https://github.com/actions/virtual-environments/issues/3287

We should update CI workflow in other repos and here.

Related:  r-hyperspec/pkg-skeleton#17

**Comment by bryanhanson** [comment]
If you can wait a few days I will fix all of these.

**Comment by bryanhanson** [comment]
Hmm I fixed it in https://github.com/cbeleites/hyperSpec/commit/6d8cf69b65eb39355fcddd5570021a8639a6c183
