### ISSUE TITLE
hy_list_available_hySpc_packages() not working

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#328]
... and the unit test fails. 

I think the resulting JSON is not properly processed.

**Comment by GegznaV** [comment]
Please, give more details on this and provide a reprex. I cannot reproduce the failure:

![image](https://user-images.githubusercontent.com/12725868/125165424-7d1c7a00-e19f-11eb-965b-d5bf726e696a.png)

**Comment by GegznaV** [comment]
I use the current `develop` branch and face no issue. Is it a platform-specific or language-specific issue?

**Comment by cbeleites** [comment]
TODO @cbeleites 

- [x] works in Console on Desktop (Linux, EN)
- [x] fails in RStudio test pane on Desktop (Linux, EN)
- [ ] check  in Console on Laptop (Linux, DE)
- [ ] check  in RStudio test pane on Laptop (Linux, DE)

**Comment by GegznaV** [comment]
@cbeleites, install r-hyperspec/hyperSpec#3 and report if this improved your issue (it is not intended to solve it completely).

By the way, does the alternative method described in the documentation of `hy_list_available_hySpc_packages()` work without errors? Or does it also result in an error and not a correct list of available packages?

**Comment by bryanhanson** [comment]
Despite recent improvements the code does not work on a Mac.  I have done some scraping of the GH api and the following code is more robust:
```
response <- GET("https://api.github.com/orgs/r-hyperspec/repos?per_page=100")
json <- content(response, "text")
json <- fromJSON(json, simplifyVector = FALSE)
repos <- unlist(lapply(json, function(x) x$name))
```
but it would introduces 2 new dependencies, `httr` and `jsonlite`.  Not sure we want to do this.  The function we are fixing is not called by any other functions as far as I can tell.  Perhaps a simpler solution is to disable the unit test on Macs.

**Comment by GegznaV** [comment]
The dependencies were the reason why this code is in description and not in the body of actual functions.

**Comment by GegznaV** [comment]
I think, that the issue is that on different machines GitHub API gives a response that is formatted in a bit different way. Please test  r-hyperspec/hyperSpec#6 and confirm that the issue is solved or help to debug the issue (instructions are in the PR).
