### ISSUE TITLE
rename vignette "introduction"?

### ISSUE THREAD

**Issue by ximeg** [cbeleites/hyperSpec#33]
R searches vignettes using their names. In the case of "introduction" the name can refer basically to any package. 

> vignette("introduction")
Warning message:
vignette ‘introduction’ found more than once,
using the one found in ‘/home/ximeg/R/x86_64-pc-linux-gnu-library/3.3/dplyr/doc’

**Comment by cbeleites** [comment]
yes, I noticed that as well. 

Ideas for the new name, please?

**Comment by bryanhanson** [comment]
I didn't even know you could just do `vignette("introduction")`!  I just tried it and I got the intro to `dendextend` so perhaps the results depend on which packages one has installed.  I always use `browseVignettes("hyperSpec")` which brings up all options.  I don't really see how `vignette("introduction")` can scale: every package would have to have a unique and knowable name, perhaps along the lines of "Intro2hyperSpec" or "Intro2ChemoSpec" but CRAN doesn't typically force this kind of thing (it's more in Bioconductor's style).

**Comment by bryanhanson** [comment]
Or, having now looked at `?vignette` one apparently can do `vignette("introduction", "hyperSpec")` which works perfectly fine for hyperSpec.  So maybe there is no problem.

**Comment by ximeg** [comment]
Allright, I didn't know one can specify the package name there... You are
right, may be there is no problem. Anyway, it's not the most important
issue ;)

Roman Kiselev

**Comment by ximeg** [comment]
What if you just call it simply "hyperSpec"? i.e.

    vignette("hyperSpec")
or / and

    vignette("hyperspec")

I bet you can not come with a better name, can you?

**Comment by cbeleites** [comment]
Go ahead (maybe better wait till we solved your pull request, and merged the other almost-ready-to-merge issue fix branches before opening a new construction site...)

**Comment by ximeg** [comment]
I have renamed the vignette in d83b422
