### ISSUE TITLE
Is this function name correnct: rmmvnorm

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#337]
@cbeleites, in file `mvtnorm.R`, is function name is spelled correctly: `rmmvnorm()`?

**Comment by cbeleites** [comment]
`mvtnorm::rmvnorm()` (with 1 m) allows a single covariance matrix.

`hyperSpec::rmmvnorm()` (with 2 m) allows *m*ultiple covariance matrices for multiple groups. 
It has methods not only for hyperSpec objects but also such a multi-group extention for numeric objects.

We can discuss what a better name would be, and the documentation could definitively do with a better description. But the name should IMHO *not* be `rmvnorm()` with a single m.

**Comment by GegznaV** [comment]
OK, now I understand it better.
Is it ok, if we added this to the description (if it is missing, I did not study the documentation very deeply):

```
mvtnorm::rmvnorm() (with 1 m) allows a single covariance matrix.

hyperSpec::rmmvnorm() (with 2 m) allows multiple covariance matrices for multiple groups.
It has methods not only for hyperSpec objects but also such a multi-group extension for numeric objects.
```

**Comment by GegznaV** [comment]
The main reason I noticed the name is that the file name does not match the function name. So, I think, the file should be renamed.

**Comment by GegznaV** [comment]
I'm closing this here as it already reopened as  r-hyperspec/hyperSpec#8
