### ISSUE TITLE
Setting spectral matrix of incorrect size destroys hyperSpec object

### ISSUE THREAD

**Issue by ximeg** [cbeleites/hyperSpec#35]
Suppose I try to set a new spectral matrix and accidentally provide a matrix of a wrong size.

```
> spc <- chondro[1]
> spc@data$spc <- matrix(1:2, ncol=2)
Error in validObject(x) : 
  invalid class “hyperSpec” object: Length of wavelength vector differs from number of data points per spectrum.
```

This results in an error message, which is understandable. But I would expect, that the `spc` object is still intact (because there was an error), however **it was modified by this operation**.
```
> spc
Error in validObject(x) : 
  invalid class “hyperSpec” object: Length of wavelength vector differs from number of data points per spectrum.
> spc@data$spc
     [,1] [,2]
[1,]    1    2
> nwl(spc)
Error in validObject(x) : 
  invalid class “hyperSpec” object: Length of wavelength vector differs from number of data points per spectrum.
```

I find this behavior really-really confusing.

**Comment by cbeleites** [comment]
Of course it does, but that doesn't have anything to do with `hyperSpec` but rather with R's class system which doesn't provide total encapsulation. You use the basic R low-level function to change the internals of the object. At that point, `hyperSpec` doesn't even have a chance of doing anything. 

But `hyperSpec` does provide a proper setter function for the spectra matrix, `[[<-`, which guarantees a valid `hyperSpec` object is returned: 
```r
spc [[]] <- matrix (1:2)
plot (spc)
```
Note, that the matrix is recycled in this example (which is done by the standard R `[<-` replace function, so I decided not to change it - although I'd be open for a pull request that implements a check whether the matrix `value` has the correct size and if not `stop`s.)
