### ISSUE TITLE
Change default color palette for `plotmap`

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#37]
Instead of giving specific functionality in `hyperSpec` this can be done via `lattice` options:

    trellis.par.set(regions = list (col = matlab.palette()))

However, this possibility should be explained in the `plotting` vignette.

**Comment by ximeg** [comment]
I have written a page in the plotting vignette that describes how to get, change and set lattice parameters, and how to make them persistent. Solved in 3d01485.
