### ISSUE TITLE
More consistent behavior for file import functions

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#38]
- [x]  rename all `scan.*` import functions to `read.*`
- [x]  deprecate the old function names
- [ ]  consistently use connections instead of file names
- [x] *(I think I forgot one point we discussed)*
- [x]  update vignettes accordingly

**Comment by eoduniyi** [comment]
@cbeleites Does this still need to be worked on?

**Comment by GegznaV** [comment]
@cbeleites, is this issue still relevant? If **no**, it should be closed.

**Comment by GegznaV** [comment]
@cbeleites, is this issue still relevant? If **yes**, it should be moved (reopened) in relevant *hySpc.read* packages.

**Comment by GegznaV** [comment]
These are related issues:

- r-hyperspec/hySpc.read.ENVI#12  
- r-hyperspec/hySpc.read.spc#11  
- r-hyperspec/hySpc.read.spe#18  
- r-hyperspec/hySpc.read.txt#43  

So I close this issue. If I missed something, please, reopen the relevant parts of this issue elsewhere.
