### ISSUE TITLE
Building does not work under Windows

### ISSUE THREAD

**Issue by mhw-hermes** [cbeleites/hyperSpec#39]
cloning the github repo and  running 'Build All' from Rstudio results in an errormessage: 

![image](https://cloud.githubusercontent.com/assets/9215671/23215317/d9eaa58c-f909-11e6-8ce8-869bdc7a37b5.png)

note: Buildtools are configured to use the makefile 

![image](https://cloud.githubusercontent.com/assets/9215671/23215222/85c52720-f909-11e6-90bd-6df308a7385d.png)

**Comment by ximeg** [comment]
You don't have GNU Make or Windows has no idea where to find it. See http://stackoverflow.com/questions/23723364/make-is-not-recognized-as-an-internal-or-external-command-operable-program-or#23734705 for details.
Install GNU Make and add it to `PATH` environment variable
