### ISSUE TITLE
Remove `cat` command from baseline fitting functions

### ISSUE THREAD

**Issue by ximeg** [cbeleites/hyperSpec#40]
Each time I use `spc.fit.poly.below`, it prints an informative message
```
> bl <- spc.fit.poly.below(chondro)
Fitting with npts.min =  15
```
This message is not really informative (at least for me), but it is very hard to get rid of. It gets especially annoying when using knitr.

![image](https://cloud.githubusercontent.com/assets/8937566/23721825/658b294c-0443-11e7-8e6a-9604d119ff6a.png)

The only real way to suppress it is to provide the `npts.min` argument, which is not obvious unless you dig into the source code. The message is produced by the following code from `spc.fit.poly.R`:

```
  if (is.null (npts.min)){
    npts.min <- max (round (nwl(fit.to) * 0.05), 3 * (poly.order + 1))
    cat ("Fitting with npts.min = ",  npts.min, "\n")    #  <----------- HERE
  } else  if (npts.min <= poly.order){
    npts.min <- poly.order + 1
    warning (paste ("npts.min too small: adjusted to", npts.min))
  }
```

I would suggest to print this message only when debuglevel is set to 1, or to remove it completely. Any other ideas?

**Comment by cbeleites** [comment]
good idea!

**Comment by ximeg** [comment]
Super, now it's much better! Thank you for a quick patch! :+1:
