### ISSUE TITLE
Warning message plotmap

### ISSUE THREAD

**Issue by mhw-hermes** [cbeleites/hyperSpec#5]
Warning messages:
1: In (function (x, y, z, subscripts, at = pretty(z), ..., col.regions = regions$col,  :
  'x' values are not equispaced; output may be wrong

occures for non corrupted data - increase debuglevel for this message to be displayed?

**Comment by cbeleites** [comment]
Michael, can you send me a minimal working example?

Thanks,

Claudia

**Comment by cbeleites** [comment]
No MWE, so I'll close the issue for now - it can be reopened once we have an example.
