### ISSUE TITLE
Vignettes chondro and fileio broken when building with R 3.4.1

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#56]
R 3.4.1 ignores the supplied pdfs in `inst/doc` which were previously used. Instead, the pdfs produced from the stub .Rnws (which were needed to get the vignettes listed in R) are used.

[This is apparently a fix of long-standing but undesired behaviour.](https://cran.r-project.org/doc/manuals/r-release/NEWS.pdf)

**Comment by cbeleites** [comment]
... `[R.rsp](https://github.com/HenrikBengtsson/R.rsp)::asis` is the way to go.

**Comment by ximeg** [comment]
Hey @cbeleites,
in your commit 917250413bc1c0d510e713b452df4731c068c961 you deleted the targets `fileio.pdf` and `chondro.pdf` from the `hyperSpec/hyperSpec/inst/doc/Makefile`, especially the lines

```
cp -av ../../../Vignettes/chondro/chondro.pdf $@
cp -av ../../../Vignettes/fileio/fileio.pdf $@
```

This leads in my case to "No rule to make target 'fileio.pdf'" error. I had to include these targets again to build the hyperSpec. I use R 3.4.2.

**Comment by cbeleites** [comment]
Hi Roman,

- please don't add them back: both vignettes are now taken care of via `R.rsp`. 
- I didn't find a solution with pdfs `/inst/doc` that did properly pass `R CMD check` and had the vignettes listed as they should be.
- `R.rsp`'s mechanism takes place in `vignettes/`: there should be 4 files, a `.pdf` and a `.pdf.asis` file for each vignette. Basically, it is a special vignette builder that just copies the provided pdf.
- So the question is rather, which other `Makefile` is still trying to put the pdfs into `/inst/doc`?

**Comment by cbeleites** [comment]
Ah, think I found it: a leftover call in `vignettes/Makefile-local`. Checking the fix now.

**Comment by cbeleites** [comment]
@ximeg : can you please check the fix? (Works for me incl. after `make superclean`)

**Comment by cbeleites** [comment]
@ximeg: ping?

**Comment by ximeg** [comment]
@cbeleites: I remember that I checked it the same day you fixed the bug and it worked perfectly. And I was pretty sure that I informed you, but apparently I didn't. Shortly: it works!
