### ISSUE TITLE
Adding function for new('hyperSpec'...)

### ISSUE THREAD

**Issue by rguliev** [cbeleites/hyperSpec#6]
Hi!
I noticed that it's pretty annoying to type 'new('hyperSpec',...)' every time. How about adding function as.hyperspec like:

```
as.hyperspec <- 
    function(X, wl = NULL, other.data = NULL, use.colnames = TRUE) {
        # if wl is setted just use it, otherwise
        if (is.null(wl)) {
            wl <- 1:ncol(X) # if use.colnames is FALSE use 1,2,3... for wavelengths
            if (use.colnames && !is.null(colnames(X))) {
                # use colnames.
                wl <- as.numeric(gsub(pattern = '[[:alpha:]]', replacement = '', x = colnames(X)))
            }
        }
        if (is.null(other.data)) {
            new('hyperSpec', spc = as.matrix(X), wavelength = wl)
        } else {
            new('hyperSpec', spc = as.matrix(X), wavelength = wl, data = other.data)
        }
    }
```
Here I use `gsub` to remove prefix characters which were added automatically because colnames can't start with numbers.Like, for example:
```
> A <- matrix(1:8, ncol = 4)
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8
> data.frame(A)
  X1 X2 X3 X4
1  1  3  5  7
2  2  4  6  8
```

**Comment by cbeleites** [comment]
Hi Rustam,

thanks for the suggestion - it is definitively a good one. I added this in branch issue-new-6 - have a look, please.
Would you be willing to contribute a bunch of unit tests (particularly for the `guess.wavelength` function?

**Comment by rguliev** [comment]
Hi!
I looked at it. It seems good. Much better than my version:)

Of course I would like to help.  I have to confess - I've never done that. So, sorry for silly questions. 
What am I supposed to do? Append something like `.test (guess.wavelength) <- function (){ <some validation of the function's work> }` to [`guesswavelength.R`](https://github.com/cbeleites/hyperSpec/blob/issue-new-6/hyperSpec/R/guesswavelength.R)? And how should I add my changes to the project?

**Comment by cbeleites** [comment]
Hi Rustam,

yes, that's basically it. Have a look at `vandermonde.R` how I usually do it (unfortunately that test doesn't have comments, but you get the basic idea). That is unit testing with `svUnit`. 

I plan to switch over completely to `testthat` in the not-too-far future - so if you prefer (or have worked with) `testthat`, you can also add the usual `test-guesswavelength.R` in `tests/testthat`. 

You can then make a pull-request (please use the issue branch, not the default master).

Many thanks.

**Comment by rguliev** [comment]
Hi,
Ok. I guess I got it. I will do that.

**Comment by cbeleites** [comment]
I had a look at the transition to `testthat` and it turned out to be pretty straightforward - so I did it already. 

Meaning that I need the unit test using `testthat` - but you can still look at `vanderMonde.R` to see how that works.

Anyways, many thanks for your help!

**Comment by rguliev** [comment]
Hi!
Started adding tests, I noticed that `as.hyperSpec` uses `guess.wavelength`, while `new(...)` doesn't. I think it's not right these functions to be able have different outputs. So, I changed functions in a way that `new` uses `guess.wavelength` and `as.hyperSpec` is just a wrapper for `new`.
You can see the changes I made in [my forked repo](https://github.com/rguliev/hyperSpec/tree/issue-new-6). What would you say? Would you agree?

Talking about testing, I've added tests for functions (I used `test_that`). They are in the repo. Although, I have not checked them yet. I faced a problem: I'm trying to run the tests by test_file, like `test_file('guesswavelength.R')`, but it returns error
``
Error in .test(guess.wavelength) <- function() { : 
  could not find function ".test<-"
``
Obviously, I have to do something with '.test'. Currently googling for it.

P.S. I'm sorry for late response. I hope it didn't bring any inconvenience.

**Comment by cbeleites** [comment]
Hi Rustam,

thanks a lot for your help. 

My thought on `as.hyperSpec ()` vs. `new ("hyperspec")` is that I'd prefer `new` not to make any guesses. Such guesses can easily be wrong, so I think it is good to have one function that is on the safe side. I see `as.hyperSpec` as a convenience function, so its purpose is to allow users to be lazy, and thus IMHO guessing the wavelength axis is appropriate there.  
(Basically similar to the subsetting where you can use hyperSpec's very own formula interface to select wavelength ranges whereas for programming, you are supposed to properly work with indexing.)

How to run the tests:

function `.test<-` is in `unittest.R` (I just fixed outdated and missing `@include` statements for that in branch master). You can run the unit tests either in the installed package by `hy.unittest()` or during package development using `devtools::test()` (RStudio: Ctrl+Shift+T if the project is properly set up for package development). This needs a working `NAMESPACE` file and  `Collate:` directive in `DESCRIPTION` which are both taken care of by `roxygen2::roxygenize` or `devtools::document ()` (RStudio: Ctrl+Shift+D) or `make roxy` at the command line.

**Comment by rguliev** [comment]
Hi,
I've changed the code according your last comment and commited the changes to my forked repo. I've been playing around running tests and package building. And I stuck with one error, which occurs in testing:
`Error: 'flu' is not an exported object from 'namespace: hyperSpec'`
Have you ever faced something like that? Any suggestions on how it should be handled?

**Comment by rguliev** [comment]
Oh, I just saw that your commit in master on Jan 12, 2017:
> fix in main Makefile  …
> building of sysdata und flu data
Probably that was the problem. I'll check that.

**Comment by cbeleites** [comment]
Am Montag, den 13.02.2017, 01:40 -0800 schrieb Rustam:
> Oh, I just saw that your commit in master on Jan 12, 2017:
> > 
> > fix in main Makefile  …
> > building of sysdata und flu data
> Probably that was the problem. I'll check that.

Yes you'll need to `make` hyperSpec and in order for that to work you
may need to pull the `git lfs` content explicitly (`git lfs pull` or
`fetch` or so). 
Didn't find the time to check and write up how it works. But maybe this
helps already. 

Cheers,
Claudia

> 
> 

-- 
Claudia Beleites Chemometric Consulting
Södeler Weg 19
61200 Wölfersheim
Germany

phone:  +49 (15 23) 1 83 74 18
e-mail: claudia.beleites@chemometrix.eu
USt-ID: DE305606151

**Comment by cbeleites** [comment]
Hi Rustam, 
can you please check the new [building instructions](https://github.com/cbeleites/hyperSpec/blob/master/README.md)?  Do they work for you?

**Comment by rguliev** [comment]
Hi,
That's of great help! I'll definitely check it, since I still struggling with building the package properly.

**Comment by rguliev** [comment]
Hi,
Finally, I've handled it!
During testing:
* I fixed some bugs in Makefiles. I didn't commit them, because it should be another branch, as I think.
* Got addional information for building instructions.
I'll sent this info soon.

P.S. Still think that `new(...)` should use `guesswavelength`, since it uses almost same code:
```
if (is.null (wavelength)){
    ## guess from spc's colnames
    if (!is.null (spc))
      wavelength <- as.numeric (colnames (spc))

    if (length (wavelength) == 0L || any (is.na (wavelength)))
      wavelength <- as.numeric (colnames (data$spc))

    if (length (wavelength) == 0L || any (is.na (wavelength)))
      wavelength <- seq_len (nwl) # guessing didn't work
  }
  .Object@wavelength <- wavelength
```

**Comment by cbeleites** [comment]
Yes, I'm convinced now, we can use `guesswavelength` also in `new`.

May I ask first, though, why you chose to return `NULL` instead of `seq_len (ncol (X))`? => That would need to be taken care of in `.initialize`.

**Comment by rguliev** [comment]
Simple examle to understand why I decided to return `NULL`. Imagine we have a spc matrix without colnames: `as.hyperSpec(matrix(1:15,ncol=5))`. In that case as.hyperSpec fails because `guess.wavelength (colnames (X))` tries to return `seq_len(colnames (X))`,i.e. `seq_len(NULL)`, which returns error and is not what we want. However, if `guess.wavelength` returns `NULL` then `new(...)` will run with `wavelength=NULL` which will result in correct wavelengths. 
I agree that it seems comfusing. As for me, we can to it in this way: return `NULL` if guess is failed. And then do `if NULL then seq_len`, i.e.
```
.initialize <- function (.Object, spc = NULL, data = NULL, wavelength = guess.wavelength (colnames (spc)), labels = NULL){
 if ( is.null (wavelength) && !is.null (spc) )
   wavelength = 1:ncol(spc)
...
}
.as.hyperSpec.matrix <- function (X, ...){
   new ("hyperSpec", spc = X, ...)
}
```

**Comment by cbeleites** [comment]
> `as.hyperSpec(matrix(1:15,ncol=5))`  
>  fails because `guess.wavelength (colnames (X))` tries to return `seq_len(colnames (X))`,i.e. `seq_len(NULL)`

but `seq_len  (ncol (X))` would be correct, wouldn't it?
And moreover that is what `.initialize` does in that case as well.

**Comment by rguliev** [comment]
Hi Claudia,
For some reasons your last comment doesn't appear in this chat. 
>> as.hyperSpec(matrix(1:15,ncol=5))
>> fails because guess.wavelength (colnames (X)) tries to return seq_len(colnames (X)),i.e. seq_len(NULL)
> 
> but seq_len (ncol (X)) would be correct, wouldn't it?
> And moreover that is what .initialize does in that case as well.

I think you should take a look at `guess.wavelength` function:
```
#' @param X character with numbers hidden inside
#'   
#' @return numeric
#' @export
#' 
#' @examples
#' tmp <- data.frame(flu [[,, 400 ~ 410]])
#' (wl <- colnames (tmp))
#' guess.wavelength (wl)
guess.wavelength <- function (X) {
```
The real question is what is `X` in `guess.wavelength`? Is it a vector or a matrix? **Currently it's a vector of colnames (which is NULL for a matrix without colnames!).** So if we try `seq_len (ncol (X))` inside guess.wavelength it will be equal to `seq_len(ncol(colnames(<some_spc_matrix>)))`.

There are two options here:
1. Described in my previus comment.
2. Create two methods: `guess.wavelength.vector` (= current `guess.wavelength`) and `guess.wavelength.matrix`:
```
guess.wavelength.matrix <- function(X) {
    wl <- guess.wavelength.vector(colnames(X))
    if (is.null(wl))
        wl <- seq_len(ncol(X))
    return(wl)
}
```

**Comment by cbeleites** [comment]
Hi Rustam,

> For some reasons your last comment doesn't appear in this chat.

it doesn't appear in the chat because I deleted it as I realized 
immediately after sending that guess.wavelength never sees the matrix 
but only the colnames...
;-)
sorry for the noise, and you are right.

Claudia




> 
> as.hyperSpec(matrix(1:15,ncol=5))
> fails because guess.wavelength (colnames (X)) tries to return 
> seq_len(colnames (X)),i.e. seq_len(NULL)
> 
> but seq_len (ncol (X)) would be correct, wouldn't it?
> And moreover that is what .initialize does in that case as well.

I think you should take a look at guess.wavelength function:

#' @param X character with numbers hidden inside
#'
#' @return numeric
#' @export
#'
#' @examples
#' tmp <- data.frame(flu [[,, 400 ~ 410]])
#' (wl <- colnames (tmp))
#' guess.wavelength (wl)
guess.wavelength <- function (X) {

The real question is what is X in guess.wavelength? Is it a vector or a 
matrix? CURRENTLY IT'S A VECTOR OF COLNAMES (WHICH IS NULL FOR A MATRIX 
WITHOUT COLNAMES!). So if we try seq_len (ncol (X)) inside 
guess.wavelength it will be equal to 
seq_len(ncol(colnames(<some_spc_matrix>))).

There are two options here:

  	* Described in my previus comment.
  	* Create two methods: guess.wavelength.vector (= current 
guess.wavelength) and guess.wavelength.matrix:

guess.wavelength.matrix <- function(X) {
     wl <- guess.wavelength.vector(colnames(X))
     if (is.null(wl))
         wl <- seq_len(ncol(X))
     return(wl)
}

**Comment by rguliev** [comment]
Hi Claudia,
Sorry, I'm a little bit confused. Are we waiting for something? :)

**Comment by rguliev** [comment]
Sorry, I don't understand how it closes the issue. It seems like a mistake, doesn't it?
