### ISSUE TITLE
Import of SPE files / support file format version 3.0

### ISSUE THREAD

**Issue by ximeg** [cbeleites/hyperSpec#65]
`hyperSpec` was tested with file format 2.5, which specifies that the SPE file consists of two parts: a 4100-long binary header, and a data block with spectral values.

The [new file format](https://trello-attachments.s3.amazonaws.com/582d750cf975da295a7f53d5/5a72ef1df3d6ae461ad99e28/61e8392fc856a02a1acb33569572b5e6/SPE_3.0_File_Format_Specification.pdf) is backwards-compatible with the previous version 2.5, and the most important for us differences are:
 * A `float32` number at offset 1992 bytes indicates the file format version. It was changed from `2.5` to `3.0`
 * A big chunk of text data in XML format was attached at the end of the file.

Currently `read.spe` cannot read new file format, as it treats **everything behind the 4100-bytes header, including the XML text, as the binary block of spectral values.**

I want to start a short discussion, what is the best way to circumvent this issue.

### My proposal:

1. Update `read.spe.header` function to read the file format version and the start of XML data (offset 678)
1. Update `read.spe`: determine size of the spectral data block from the fields `xdim` / `ydim` / `numFrames` / `datatype` in the header and stop reading at the end of the data block, before the XML header.
1. Create function `read.spe.xml` that checks the file format version and returns the XML data if format version is >=3.0. We can add package `XML` as an optional dependency. If it is available, the function will return the pretty-printed XML object. I think we should not try to process the XML any further – let the users do what they want with it. Also I suppose that the XML DOM structure may vary, as it is not rigorously described in the specification.

**Comment by ximeg** [comment]
The feature is implemented and is ready to be merged

**Comment by cbeleites** [comment]
merged now.
