### ISSUE TITLE
`read.txt.Shimadzu` overhaul needed

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#67]
- [ ] add unit test for (old) GCxGC-MS example spectrum
- [ ] get `read.txt.Shimadzu` working with the new UV-VIS-NIR example spectrum
- [ ] documentation: fileio vignette

**Comment by GegznaV** [comment]
Closing this in favor of https://github.com/r-hyperspec/hySpc.read.txt/issues/33
