### ISSUE TITLE
Feature request: online documentation with pkgdown or similar

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#78]
Package [**pkgdown**](http://pkgdown.r-lib.org/) enables the possibility to create a website with online documentation. [GitHub Pages](https://pages.github.com/) can be used to host the website.

I would be really convenient if `hyperSpec` had this kind of feature thus I suggest creating it.

**Comment by cbeleites** [comment]
I like the idea :-) :+1:, but won't have time to do much in this line myself. But I'd highly appreciate if you'd do it - so I assigned it to you.

**Comment by cbeleites** [comment]
I started to change roxygen docs to markdown when I touch some doc. A mix of old latex-style and markdown roxygen comments (per function) works fine, and I expect that this may help with pkgdown as well.

**Comment by cbeleites** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pkgdown](https://trello.com/c/jDLhstkW/40-pkgdown)

**Comment by ximeg** [comment]
As far as I understand, articles (or webpages) created with `pkgdown` would reside in a subfolder of the same repository, but they will not be built and packaged into the installable `hyperSpec`, and thus will not be installed on the end user machine. They would be a subject to a separate build process.  They would not be checked on CRAN, and thus could not be a reason for a package removal.

So, to ensure consistency, the article built with `pkgdown` should be checked by their writers and by the continuous integration system on a regular basis.

**Comment by GegznaV** [comment]
> So, to ensure consistency, the article built with pkgdown should be checked by their writers and by the continuous integration system on a regular basis.

Only a few setup files should be added for `pkgdown`  website.  Besides this, it is automatically created form the materials in the package: basically, from README.md file, Rd files, and vignettes (.Rmd files).  So the maintenance of these files equals the maintenance of the contents of the website.

> They would be a subject to a separate build process.

It could be easily automated with "GitHub actions" which is a free service for open-source projects and integrated with GitHub. To create an appropriate setup with standard `pkgdown` build procedures is as easy as
```r
usethis::use_github_action("pkgdown")
```
The website could be automatically rebuilt every time when, e.g., the main branch is updated.

**Problem.**
But the structure of the package should be appropriate. This is one of the reasons why I started to translate vignettes to Rmd.  We should discuss more on this topic (unfortunately, I'm quite busy these days and will have more time for this in a few weeks).


> continuous integration system

I suggest using GitHub actions for continuous integration (CI), and appropriate setup could be made by one of these options:
```r
usethis::use_github_action_check_standard()
usethis::use_github_action_check_release()
usethis::use_github_action_check_full()
```

 (I think, a separate issue could be created for the discussion about CI related topics)

**Comment by GegznaV** [comment]
> would reside in a subfolder

It would reside on a separate branch `gh-pages`

**Comment by ximeg** [comment]
@GegznaV Thank you very much for clarifications!

**Comment by eoduniyi** [comment]
Following the above discussion I applied `pkgdown` to `hyperSpec.skeleton`:

```R
install.packages("pkgdown")
```

    also installing the dependency 'highlight'



    The downloaded binary packages are in
    	/var/folders/4_/gg3mjn693bz4v5w1sxh71rtc0000gp/T//RtmpFMJVnd/downloaded_packages

```R
library(pkgdown)
library(devtools)
```

    Loading required package: usethis


    Attaching package: 'devtools'


    The following object is masked from 'package:pkgdown':

        build_site


```R
usethis::use_github_action("pkgdown")
```

    v Setting active project to '/Users/erickoduniyi/Documents/Projects/open-source/hyperspec/hyperSpec.skeleton'

    v Creating '.github/'

    v Adding '^\\.github$' to '.Rbuildignore'

    v Adding '*.html' to '.github/.gitignore'

    v Creating '.github/workflows/'

    v Writing '.github/workflows/pkgdown.yaml'

```R
pkgdown::build_site()
```

    -- Installing package into temporary library -----------------------------------
    == Building pkgdown site =======================================================
    Reading from: '/Users/erickoduniyi/Documents/Projects/open-source/hyperspec/hyperSpec.skeleton'
    Writing to:   '/Users/erickoduniyi/Documents/Projects/open-source/hyperspec/hyperSpec.skeleton/docs'
    -- Initialising site -----------------------------------------------------------
    -- Building home ---------------------------------------------------------------
    -- Building function reference -------------------------------------------------
    Loading required package: hyperSpec
    Loading required package: lattice
    Loading required package: grid
    Loading required package: ggplot2
    Loading required package: xml2
    Package hyperSpec, version 0.99-20200515

    To get started, try
       vignette ("hyperspec")
       package?hyperSpec
       vignette (package = "hyperSpec")

    If you use this package please cite it appropriately.
       citation("hyperSpec")
    will give you the correct reference.

    The project homepage is http://hyperspec.r-forge.r-project.org


    Loading required package: dplyr

    Attaching package: 'dplyr'

    The following object is masked from 'package:hyperSpec':

        collapse

    The following objects are masked from 'package:stats':

        filter, lag

    The following objects are masked from 'package:base':

        intersect, setdiff, setequal, union

    Loading required package: magrittr

    Attaching package: 'hyperSpec.skeleton'

    The following object is masked from 'package:hyperSpec':

        qplotspc

    Reading 'man/qplotspc.Rd'
    Reading 'man/unittests.Rd'
    == DONE ========================================================================

**Which generated the following files:**
<img width="1439" alt="Screen Shot 2020-05-19 at 2 57 32 AM" src="https://user-images.githubusercontent.com/31193655/82304028-64d91280-9981-11ea-8c4e-073fb98dd901.png">

**And the static webpage:**
<img width="1437" alt="Screen Shot 2020-05-19 at 2 57 20 AM" src="https://user-images.githubusercontent.com/31193655/82304060-6f93a780-9981-11ea-908a-de690b7dddf1.png">

Which can be viewed [here](https://eoduniyi.github.io/hyperSpec.skeleton/)

**Comment by GegznaV** [comment]
It is not useful to create a `pkgdown` website yet as the folder structure of the package is not appropriate. No useful contents are added.
But from the technical side, it is nice to know that in this situation `pkgdown` works at all.

**Comment by GegznaV** [comment]
At first, we have to get rid of make  #132

**Comment by cbeleites** [comment]
yes - unfortunately I don't think we sign dependencies between the issues
