### ISSUE TITLE
Translate vignettes from `Sweave` to `R Markdown`

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#79]
Vignettes are in LaTeX/Sweave, and should be translated into markdown and building by `knitr`.

- branch `knitr-vignettes` already exists. 

- [x] flu
- [x] laser
- [x] baseline  
- [x] chondro  
- [x] hyperspec
- [x] plotting
- [x] fileio
  - [x] untangle historic mix with unit tests into vignette and unit tests

**Comment by GegznaV** [comment]
@cbeleites, which of the following do you mean?

- **(A)** to translate vignettes to R markdown (*.Rmd*) and in the future maintain only *.Rmd* versions or 
- **(B)** write a script that translates from *.Rnw* to *.Rmd* and maintain both?

A year ago I started writing a script, but it was challenging to make a perfect translation. There were elements that did some `hyperSpec`-specific translations in my code but I didn't have time to finish it.
Today I found a package, which has function `rnw2rmd()` but have not check yet if it performs well: [roxyPackage](https://reaktanz.de/?c=hacking&s=roxyPackage#noCRAN).

If our goal is **(A)**, then we can use either of the scripts (or even combine both) and they, hopefully, will do 80% of the translation automatically. The remaining can be done manually.

If our goal is **(B)**, we need to write a better hyperSpec-specific script.

So, what's the goal?

**Comment by GegznaV** [comment]
Next question: is the branch `knitr-vignettes` really up to date? It was updated on Feb 12 and:

> This branch is 8 commits ahead, 37 commits behind master.

**Comment by cbeleites** [comment]
@GegznaV 

- the goal is **(A)**: translate once, and use .Rmd in future. 
- no the branch wasn't up to date, I had forgotten to push and was then stuck with so slow internet connection that I couldn't push due to time outs. 

Thanks for chiming in :+1:

**Comment by GegznaV** [comment]
Currently, I noticed the activity in the `hyperSpec` repository. To avoid several people working on the same features, I want to announce that I'm currently translating the vignettes to R Markdown.

When the R Markdown vignettes are ready, I'd like to return to #78

**Comment by cbeleites** [comment]
Hi Vilmantas,
great job! 
Yes, I'm active: I got busy with a first go on the dplyr interface and in consequence needed some updates (and found some bugs and took care of a few more) in hyperSpec.
I'll keep away from the vignettes (mostly - I did insert a paragraph into the hyperSpec vignette about `droplevels`).
Many thanks for your help!

**Comment by GegznaV** [comment]
As translation fo vignettes to Rmd and creation of unit tests are two separate topics, let's keep this for translation only and  #174 is for unit tests.
