### ISSUE TITLE
wl.range in qplotspc

### ISSUE THREAD

**Issue by martinEcarnot** [cbeleites/hyperSpec#83]
Hello. Thanks for this package.

`qplotspc(chondro)`
is working well 
but

`qplotspc(chondro,wl.range=1000:1500)`
Shows the following error

> Error in qplotspc(chondro, wl.range = 1000:1500) : 
  internal error in qplotspc: 0 range. Please contact the package maintainer.

**Comment by rguliev** [comment]
Hi,
You can use `qplotspc(chondro[,,1000~1500])` as a workaround.

**Comment by cbeleites** [comment]
@rguliev thanks for supplying the quick workaround.
@martinEcarnot can you provide some more details (sessionInfo)?

for me (hyperSpec_0.99-20180827, ggplot2_3.0.0), `qplotspc(chondro,wl.range=1000~1500)` works as expected!?

**Comment by martinEcarnot** [comment]
Ok, here is the result of 

`sessionInfo()`
> R version 3.4.4 (2018-03-15)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 18.04.1 LTS
> 
> Matrix products: default
> BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
> LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
> 
> locale:
>  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
>  [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] grid      stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] asdreader_0.1-3         FactoMineR_1.36         prospectr_0.1.3         RcppArmadillo_0.8.500.0
>  [5] factoextra_1.0.5        pls_2.6-0               signal_0.7-6            hyperSpec_0.99-20171005
>  [9] ggplot2_3.1.0           lattice_0.20-38        
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.18         ggpubr_0.1.5         pillar_1.1.0         compiler_3.4.4       RColorBrewer_1.1-2  
>  [6] plyr_1.8.4           bindr_0.1            iterators_1.0.8      tools_3.4.4          digest_0.6.15       
> [11] testthat_2.0.0       tibble_1.4.2         gtable_0.2.0         pkgconfig_2.0.1      rlang_0.2.1         
> [16] foreach_1.4.3        ggrepel_0.7.0        yaml_2.1.19          bindrcpp_0.2         cluster_2.0.7-1     
> [21] withr_2.1.2          dplyr_0.7.4          knitr_1.20           flashClust_1.01-2    scatterplot3d_0.3-40
> [26] glue_1.2.0           R6_2.2.2             latticeExtra_0.6-28  purrr_0.2.5          magrittr_1.5        
> [31] leaps_3.0            scales_0.5.0         codetools_0.2-15     MASS_7.3-50          assertthat_0.2.0    
> [36] colorspace_1.3-2     labeling_0.3         lazyeval_0.2.0       munsell_0.4.3

**Comment by cbeleites** [comment]
@martinEcarnot did updating help?

**Comment by martinEcarnot** [comment]
Yes it works perfectly!
Thanks a lot.

**Comment by cbeleites** [comment]
Glad everything works again!
