### ISSUE TITLE
consistent naming of wavelength parameters

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#90]
Currently the wavelength slot is referred by parameters called 

- [ ] `.wavelength`, 
- [ ] `wavelength`, 
- [ ] `wavelengths` 

or `wl`.

Change to consistently use `wl`.

- the label for the units is `.wavelength`   
  what shall we do here?
  - keep as it is?
  - `.wavelength` gives minimal (informal) safety of not conflicting with the label of a column `wavelength` (I'm thinking e.g. fluorescence, where a user may record excitation wavelength for the emission spectra)
  - rename to `wavelength` to be consistent with the slot name?
  - make it its own slot to be rid of all correponding problems? (major refactoring - but now before release 1.0 would be the occasion to do it)

**Comment by GegznaV** [comment]
Issue moved and reopened as:
- https://github.com/r-hyperspec/hyperSpec/issues/14
