### ISSUE TITLE
Issues related to "deldir"

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#92]
I'm not sure if it is serious, but the following code returns these warning messages:

```r
plotvoronoi(sample(chondro, 300), clusters ~ x * y)
#> 
#>      PLEASE NOTE:  The components "delsgs" and "summary" of the
#>  object returned by deldir() are now DATA FRAMES rather than
#>  matrices (as they were prior to release 0.0-18).
#>  See help("deldir").
#>  
#>      PLEASE NOTE: The process that deldir() uses for determining
#>  duplicated points has changed from that used in version
#>  0.0-9 of this package (and previously). See help("deldir").
```

**Comment by cbeleites** [comment]
No, this is not serious. 

The "newer" change in release 0.0.-18 actually happened some 7 1/2 years ago, and hyperSpec is anyways only indirectly affected as it calls `lattice::panel.voronoi()` rather than doing any direct calls to a triangulation function.
