### ISSUE TITLE
Error in .rubberband() if the first intensity value in a spectrum is NA

### ISSUE THREAD

**Issue by henningte** [cbeleites/hyperSpec#95]
Hi,

I've spotted a minor bug in `.rubberband()` that occurs if a spectrum where the first intensity value is `NA` is used.

The error message is:
`Error in 1:which(pts == 1) : argument of length 0`

I've also searched the source code to understand and find the error. The error occurs at line 66 in spc.rubberband.R because `pts` does not contain `1` if the first intensity value is `NA`.

A possible solution would be to replace `pts <- pts [1 : which (pts == 1)]` in line 66 by `pts <- pts [1 : which.min(pts)]`.

Here is a reproducible example for the bug:
 ```
library(hyperSpec)

# toy spectrum with NA intensity value in the first row
x_hs <- methods::new("hyperSpec", 
                     spc = matrix(c(NA, -(2:100)^2), nrow = 1), 
                     wavelength = 1:100)

# try rubberband correction
x_bl <- spc.rubberband(x_hs,
                       spline = FALSE,
                       df = 30)
```

**Comment by cbeleites** [comment]
A related bug happens when the **last** point of a spectum is `NA`.

**Comment by henningte** [comment]
@cbeleites,

thanks for your fast response!

Yes, that's true. So wouldn't it be also sensible to change `imax <- which (pts == ncol (y)) - 1` in line 59 to `imax <- which.max(pts) - 1`?

For this example this suggestion (in addition to my previous one) works at least:
```
library(hyperSpec)

# toy spectrum with NA intensity value in the first row
x_hs <- methods::new("hyperSpec", 
                    spc = matrix(c(NA, -(2:99)^2, NA), nrow = 1), 
                    wavelength = 1:100)
```

**Comment by cbeleites** [comment]
yes and a further change was needed in l. 78

**Comment by cbeleites** [comment]
Should work now.

**Comment by henningte** [comment]
Yes, it works now. Thanks!
