### ISSUE TITLE
dependency on orphaned package **XML**

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec#98]
Checking on **R-devel** warns that **hyperSpec** depends on **XML** which is deprecated.

As far as I can see, the only point where this happens is `read.spe.xml()`, and only if flag `as.xml.object` is `TRUE`. Then, instead of returning the character (unparsed XML), the parsed XML object is returned.

On CRAN, I don't see **XML** listed as orphaned (r-core seems to maintain it). 

## proposed solution

Use **xml2** instead of **XML**.

@ximeg: do you have an opinion?

**Comment by ximeg** [comment]
@cbeleites I am going to investigate this tomorrow. Hold on :)

**Comment by cbeleites** [comment]
I called Flo and Clara (they send greetings): they told me `read.spe()` is in use but to their knowledge noone there uses `read.spe.xml()`.

I don't know whether anyone uses your RomanRaman-related code there, nor whether a change in `read.spe.xml()` would break it. That is probably the main input I need from you here. 

We need to have **hyperSpec** back on CRAN when we write/publish the GSoC project - and it's high time to do that now according to my experience with GSoC.

**Comment by ximeg** [comment]
Done, please merge and close this issue :)
